# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvfiles', '0003_auto_20171107_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='report_date',
            field=models.DateTimeField(),
        ),
    ]
