# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 21:00
from __future__ import unicode_literals

from django.db import migrations, models


def do_thing(apps, schema_editor):
    """ fill all end dates with start date """
    File = apps.get_model('csvfiles', 'File')
    all_files = File.objects.all()

    for f in all_files:
        if f.report_end_date is None:
            f.report_end_date = f.report_start_date
            f.save()


class Migration(migrations.Migration):

    dependencies = [
        ('csvfiles', '0003_auto_20171108_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='report_date',
            new_name='report_start_date',
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Export Wins'), (2, 'FDI Investments Monthly'), (3, 'FDI Investments Daily'), (4, 'Service Deliveries Monthly'), (
                5, 'Service Deliveries Daily'), (6, 'Contacts for Regions'), (7, 'Contacts for Sectors'), (8, 'Companies for Regions'), (9, 'Companies for Sectors')]),
        ),
        migrations.AddField(
            model_name='file',
            name='report_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(do_thing),
    ]
