# Generated by Django 2.0.1 on 2018-01-17 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csvfiles', '0004_auto_20171121_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Export Wins'), (2, 'FDI Investments Monthly'), (3, 'FDI Investments Daily'), (4, 'Service Deliveries Monthly'), (5, 'Service Deliveries Daily'), (6, 'Contacts for Regions'), (7, 'Contacts for Sectors'), (8, 'Companies for Regions'), (9, 'Companies for Sectors'), (10, 'Kantar Report Monthly')]),
        ),
        migrations.AlterField(
            model_name='file',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
