# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdi', '0002_auto_20170914_1132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Investments',
        ),
    ]
