# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdi', '0003_delete_investments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(db_index=True, max_length=255)),
                ('stage', models.CharField(max_length=255)),
                ('number_new_jobs', models.PositiveIntegerField(default=0)),
                ('number_safeguarded_jobs', models.PositiveIntegerField(default=0)),
                ('approved_high_value', models.BooleanField(default=False)),
                ('approved_good_value', models.BooleanField(default=False)),
                ('date_won', models.DateField()),
                ('sector_team', models.CharField(max_length=255)),
                ('uk_region', models.CharField(max_length=255)),
                ('client_relationship_manager', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_reference', models.CharField(max_length=255)),
                ('investment_value', models.PositiveIntegerField(default=0)),
                ('foreign_equity_investment', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
