# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 15:14
from __future__ import unicode_literals

from django.db import migrations

forward1 = """
CREATE INDEX CONCURRENTLY idx_fdi_investmentlegacyload_data on fdi_investmentlegacyload
USING gin ((data -> 'Project Reference Code'));
"""

forward2 = """
CREATE INDEX CONCURRENTLY idx_fdi_companyload_data on fdi_companylegacyload
USING gin ((data -> 'Project Reference Code'));

"""

reverse1 = """
DROP INDEX idx_fdi_investmentlegacyload_data;
"""
reverse2 = """
DROP INDEX idx_fdi_companyload_data;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('fdi', '0004_investments'),
    ]

    operations = [
        migrations.RunSQL(forward1, reverse_sql=reverse1),
        migrations.RunSQL(forward2, reverse_sql=reverse2)
    ]
    atomic = False
