# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdi', '0005_auto_20170920_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='legacy',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
