# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdi', '0006_investments_legacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='foreign_equity_investment',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='investments',
            name='investment_value',
            field=models.BigIntegerField(default=0),
        ),
    ]
