# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdi', '0007_auto_20170925_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='company_country',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
