# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdi', '0007_auto_20170925_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentload',
            name='transformed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
