# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdi', '0008_investmentload_transformed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='date_won',
            field=models.DateField(null=True),
        ),
    ]
