# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdi', '0008_investments_company_country'),
        ('fdi', '0009_auto_20170929_0956'),
    ]

    operations = [
    ]
