# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 16:31
from __future__ import unicode_literals

from django.db import migrations

forward_sql = """
CREATE OR REPLACE FUNCTION get_financial_year
  (_date date)
  RETURNS VARCHAR(20)
  IMMUTABLE
  AS $$
  BEGIN
      IF (EXTRACT(month from _date) < 4) THEN
        RETURN ((EXTRACT(year from _date) - 1) || '-' || (EXTRACT(year from _date) - 2000))::VARCHAR(20) ;
      ELSE
        RETURN (EXTRACT(year from _date) || '-' || (EXTRACT(year from _date) + 1 - 2000))::VARCHAR(20) ;
      END IF;
  END;
  $$ LANGUAGE plpgsql;

CREATE INDEX IF NOT EXISTS idx_fdi_investment_fy ON fdi_investments (get_financial_year(date_won));
"""

reverse_sql = """
DROP INDEX idx_fdi_investment_fy CASCADE;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('fdi', '0010_merge_20171003_0941'),
    ]

    operations = [
        migrations.RunSQL(forward_sql, reverse_sql=reverse_sql)
    ]
