# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdi', '0012_fdiglobaltargets'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='client_relationship_manager_team',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
