# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fdi', '0013_investments_client_relationship_manager_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fdiglobaltargets',
            name='financial_year',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mi.FinancialYear'),
        ),
    ]
