# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdi', '0014_auto_20171010_1322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FDIGlobalTargets',
            new_name='GlobalTargets',
        ),
    ]
