# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fdi', '0016_country_sector_ukregion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fdi.Country')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fdi.Market')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hvc_target', models.IntegerField()),
                ('non_hvc_target', models.IntegerField()),
                ('financial_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mi.FinancialYear')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='fdi.Market')),
                ('sector_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='fdi.Sector')),
            ],
        ),
        migrations.RemoveField(
            model_name='investments',
            name='company_country',
        ),
        migrations.AddField(
            model_name='investments',
            name='company_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fdi.Country'),
        ),
        migrations.RemoveField(
            model_name='investments',
            name='sector_team',
        ),
        migrations.AddField(
            model_name='investments',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fdi.Sector'),
        ),
        migrations.RemoveField(
            model_name='investments',
            name='uk_region',
        ),
        migrations.AddField(
            model_name='investments',
            name='uk_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fdi.UKRegion'),
        ),
        migrations.AddField(
            model_name='market',
            name='countries',
            field=models.ManyToManyField(through='fdi.MarketCountry', to='fdi.Country'),
        ),
    ]
