# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fdi', '0017_auto_20171012_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorTeam',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SectorTeamSector',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='fdi.Sector')),
                ('team', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='fdi.SectorTeam')),
            ],
        ),
        migrations.AddField(
            model_name='sectorteam',
            name='sectors',
            field=models.ManyToManyField(
                through='fdi.SectorTeamSector', to='fdi.Sector'),
        ),
    ]
