# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 22:15
from __future__ import unicode_literals

from django.db import migrations


def add_sector_teams(apps, schema_editor):
    SectorTeam = apps.get_model('fdi', 'SectorTeam')
    sector_teams = ['sector1', 'sector2', 'sector3', 'sector4']
    for team in sector_teams:
        SectorTeam(name=team).save()


def add_sector_team_sector_mapping(apps, schema_editor):
    SectorTeam = apps.get_model('fdi', 'FinancialYear')
    Sector = apps.get_model('fdi', 'Sector')
    SectorTeamSector = apps.get_model('fdi', 'SectorTeamSector')

    mapping = {'sector_team_1': ['sector1', 'sector2'],
               'sector_team_2': ['sector3', 'sector4'], }

    for team, sector_list in mapping.items():
        sector_team = SectorTeam.objects.get(name=team)
        for s in sector_list:
            sector = Sector.objects.get(name=s)
            SectorTeamSector(team=sector_team, sector=sector).save()


class Migration(migrations.Migration):

    dependencies = [
        ('fdi', '0017_auto_20171012_1037'),
    ]

    operations = [
        migrations.RunPython(add_sector_teams),
        migrations.RunPython(add_sector_team_sector_mapping),
    ]
