# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 10:38
from __future__ import unicode_literals

from django.db import migrations


def run_sector_country_import(apps, schema_editor):
    from django.core.management import call_command
    call_command('import_and_transform_metadata', verbose=False)


class Migration(migrations.Migration):

    dependencies = [
        ('fdi', '0018_auto_20171012_1430'),
    ]

    operations = [
        migrations.RunPython(run_sector_country_import),
    ]
