# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 22:27
from __future__ import unicode_literals

from django.db import migrations


def add_markets(apps, schema_editor):
    Market = apps.get_model('fdi', 'Market')
    Country = apps.get_model('fdi', 'Country')
    MarketCountry = apps.get_model('fdi', 'MarketCountry')

    markets = {
        'Australia & New Zealand': 'Australia|New Zealand', 'Austria': 'Austria',
        'Belgium (& Lux)': 'Belgium|Luxembourg', 'Canada': 'Canada', 'China': 'China',
        'Denmark': 'Denmark', 'Finland': 'Finland', 'France': 'France', 'Germany': 'Germany',
        'Hong Kong': 'Hong Kong', 'India': 'India', 'Ireland': 'Ireland', 'Israel': 'Israel',
        'Italy': 'Italy', 'Japan': 'Japan', 'Netherlands': 'Netherlands', 'Norway': 'Norway',
        'Portugal': 'Portugal', 'Singapore': 'Singapore', 'South Korea': 'South Korea', 'Spain': 'Spain',
        'Sweden': 'Sweden', 'Switzerland': 'Switzerland', 'Turkey': 'Turkey', 'United States': 'United States',
        'Spain & Italy': 'Spain|Italy', 'France & Italy & Spain & Israel': 'France|Italy|Spain|Israel',
        'Portugal & Italy': 'Portugal|Italy', 'Brazil & Mexico & Argentina': 'Brazil|Mexico|Argentina',
        'China & Hong Kong': 'China|Hong Kong', 'UAE & Bahrain & Kuwait & Qatar & Saudi Arabia':
        'UAE|Bahrain|Kuwait|Qatar|Saudi Arabia', 'Mexico & Brazil': 'Mexico|Brazil',
        'Sweden & Finland & Norway & Estonia': 'Sweden|Finland|Norway|Estonia',
        'Brazil & Mexico & Argentina & Chile & Colombia': 'Brazil|Mexico|Argentina|Chile|Colombia',
        'Baltics (Est, Lat, Lith) & Sweden & Finland & Norway & Denmark & Iceland': 'Estonia|Latvia|Lithuania|Sweden|Finland|Norway|Denmark|Iceland',
        'Bulgaria': 'Bulgaria', 'Croatia': 'Croatia', 'Czech Republic': 'Czech Republic', 'Hungary': 'Hungary',
        'Poland': 'Poland', 'Romania': 'Romania', 'Slovakia': 'Slovakia', 'Slovenia': 'Slovenia',
        'Argentina': 'Argentina', 'Brazil': 'Brazil', 'Chile': 'Chile', 'Colombia': 'Colombia',
        'Mexico': 'Mexico', 'Peru': 'Peru', 'Bahrain': 'Bahrain', 'Kuwait': 'Kuwait', 'Qatar': 'Qatar',
        'Saudi Arabia': 'Saudi Arabia', 'UAE': 'UAE', 'Baltics (Est, Lat, Lith)': 'Estonia|Latvia|Lithuania',
        'Iceland': 'Iceland', 'Taiwan': 'Taiwan', 'Malaysia': 'Malaysia', 'Philippines': 'Philippines',
        'Thailand': 'Thailand', 'South Africa': 'South Africa', 'Kazakhstan': 'Kazakhstan', 'Russia': 'Russia'}

    for market_name, countries_str in markets.items():
        Market(name=market_name).save()
        market = Market.objects.get(name=market_name)
        countries = countries_str.split("|")
        for country_name in countries:
            country = Country.objects.get(name=country_name)
            MarketCountry(market=market, country=country).save()


class Migration(migrations.Migration):

    dependencies = [
        ('fdi', '0018_auto_20171012_2215'),
    ]

    operations = [
        migrations.RunPython(add_markets),
    ]
