# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fdi', '0021_auto_20171012_2227'),
    ]

    operations = [
        migrations.DeleteModel(name='Target'),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('hvc_target', models.IntegerField()),
                ('non_hvc_target', models.IntegerField()),
                ('financial_year', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='mi.FinancialYear')),
                ('market', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='fdi.Market')),
                ('sector_team', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='fdi.SectorTeam')),
            ],
        ),
    ]
