# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fdi', '0024_auto_20180116_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='FDIValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('disabled_on', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvestmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('disabled_on', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Involvement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('disabled_on', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecificProgramme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('disabled_on', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='investments',
            name='fdi_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fdi.FDIValue'),
        ),
        migrations.AddField(
            model_name='investments',
            name='investment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fdi.InvestmentType'),
        ),
        migrations.AddField(
            model_name='investments',
            name='level_of_involvement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fdi.Involvement'),
        ),
        migrations.AddField(
            model_name='investments',
            name='specific_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fdi.SpecificProgramme'),
        ),
    ]
