# Generated by Django 2.0.1 on 2018-01-22 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fdi', '0025_auto_20180118_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaltargets',
            name='financial_year',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='mi.FinancialYear'),
        ),
        migrations.AlterField(
            model_name='investments',
            name='company_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fdi.Country'),
        ),
        migrations.AlterField(
            model_name='investments',
            name='fdi_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fdi.FDIValue'),
        ),
        migrations.AlterField(
            model_name='investments',
            name='investment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fdi.InvestmentType'),
        ),
        migrations.AlterField(
            model_name='investments',
            name='level_of_involvement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fdi.Involvement'),
        ),
        migrations.AlterField(
            model_name='investments',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fdi.Sector'),
        ),
        migrations.AlterField(
            model_name='investments',
            name='specific_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fdi.SpecificProgramme'),
        ),
        migrations.AlterField(
            model_name='marketcountry',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fdi.Country'),
        ),
        migrations.AlterField(
            model_name='marketcountry',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fdi.Market'),
        ),
        migrations.AlterField(
            model_name='sectorteamsector',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fdi.Sector'),
        ),
        migrations.AlterField(
            model_name='sectorteamsector',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fdi.SectorTeam'),
        ),
        migrations.AlterField(
            model_name='target',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mi.FinancialYear'),
        ),
        migrations.AlterField(
            model_name='target',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='fdi.Market'),
        ),
        migrations.AlterField(
            model_name='target',
            name='sector_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='fdi.SectorTeam'),
        ),
    ]
