# Generated by Django 2.0.2 on 2018-02-08 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fdi', '0026_auto_20180122_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketGroupMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fdi.Market')),
                ('market_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fdi.MarketGroup')),
            ],
        ),
        migrations.CreateModel(
            name='MarketTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField(null=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mi.FinancialYear')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_targets', to='fdi.Market')),
                ('sector_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_targets', to='fdi.SectorTeam')),
            ],
        ),
        migrations.CreateModel(
            name='SectorTeamTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hvc_code', models.CharField(max_length=5)),
                ('target', models.IntegerField(null=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mi.FinancialYear')),
                ('market_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sector_targets', to='fdi.MarketGroup')),
                ('sector_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sector_targets', to='fdi.SectorTeam')),
            ],
        ),
        migrations.RemoveField(
            model_name='target',
            name='financial_year',
        ),
        migrations.RemoveField(
            model_name='target',
            name='market',
        ),
        migrations.RemoveField(
            model_name='target',
            name='sector_team',
        ),
        migrations.AddField(
            model_name='investments',
            name='hvc_code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.DeleteModel(
            name='Target',
        ),
        migrations.AddField(
            model_name='marketgroup',
            name='markets',
            field=models.ManyToManyField(through='fdi.MarketGroupMarket', to='fdi.Market'),
        ),
    ]
