# Generated by Django 2.0.2 on 2018-02-13 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fdi', '0027_auto_20180208_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketGroupCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fdi.Country')),
            ],
        ),
        migrations.RemoveField(
            model_name='marketgroupmarket',
            name='market',
        ),
        migrations.RemoveField(
            model_name='marketgroupmarket',
            name='market_group',
        ),
        migrations.RemoveField(
            model_name='marketgroup',
            name='markets',
        ),
        migrations.DeleteModel(
            name='MarketGroupMarket',
        ),
        migrations.AddField(
            model_name='marketgroupcountry',
            name='market_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fdi.MarketGroup'),
        ),
        migrations.AddField(
            model_name='marketgroup',
            name='countries',
            field=models.ManyToManyField(through='fdi.MarketGroupCountry', to='fdi.Country'),
        ),
    ]
