# Generated by Django 2.0.2 on 2018-02-14 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fdi', '0028_auto_20180213_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverseasRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OverseasRegionMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fdi.Market')),
                ('overseas_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fdi.OverseasRegion')),
            ],
        ),
        migrations.AddField(
            model_name='overseasregion',
            name='markets',
            field=models.ManyToManyField(through='fdi.OverseasRegionMarket', to='fdi.Market'),
        ),
    ]
