version: "3"
services:
  ew:
    build:
      context: .
    env_file: .env
    volumes:
      - ".:/app"
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    volumes:
      - "./:/app"

  postgres:
    image: postgres:10
    env_file: .env
    ports:
      - "5432:5432"

  redis:
    image: redis:3.2
    ports:
      - "6379:6379"