version: "3"
services:
  redis:
    image: redis

  sut:
    build:
      context: .
    env_file: .env
    volumes:
      - ".:/app"
    depends_on:
      - postgres

  # There appears to be Postgres-specific SQL in the migrations so we need a Postgres instance
  # for testing rather than sqlite.
  postgres:
    image: postgres:10
    env_file: .env
