# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 15:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default={}, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
