version: 2

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: python:3.6.9
        environment:
          SECRET_KEY: data-secret-1
          ADMIN_SECRET: data-secret-2
          UI_SECRET: data-secret-3
          MI_SECRET: data-secret-4
          DATA_SECRET: data-secret-5
          EMAIL_HOST: 127.0.0.1
          EMAIL_PORT: 1025
          DEBUG: True
          API_DEBUG: True
          DATABASE_URL: 'postgres://postgres@127.0.0.1:5432/export-wins-data'
          VCAP_SERVICES: '{"redis": [{"credentials": {"uri": "redis://127.0.0.1:7000/"}}]}'
          HAWK_IP_WHITELIST: 1.2.3.4
          HAWK_ACCESS_KEY_ID: some-id
          HAWK_SECRET_ACCESS_KEY: some-secret
          AWS_KEY_CSV_READ_ONLY_ACCESS: aws-read-key
          AWS_SECRET_CSV_READ_ONLY_ACCESS: aws-read-secret
          AWS_REGION_CSV: aws-region
          SESSION_COOKIE_SECURE: False
      - image: postgres:10
        environment:
          POSTGRES_DB: export-wins-data
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - restore_cache:
          name: Restore pip cache
          key: v1-export-wins-data-{{ checksum "requirements.txt" }}
          paths:
            - ~/cache/pip
      - run:
          name: Install dependencies
          command: python -m pip install --cache-dir ~/cache/pip --progress-bar off -r requirements.txt
      - save_cache:
          name: Save pip cache
          key: v1-export-wins-data-{{ checksum "requirements.txt" }}
          paths:
            - ~/cache/pip
      - run:
          name: Run tests
          command: python -W ignore manage.py test

workflows:
  version: 2
  build:
    jobs:
      - build
