# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-29 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi', '0028_auto_20170222_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='mi.Country'),
        ),
    ]
