# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-29 11:58
from __future__ import unicode_literals

from django.db import migrations, models


def do_thing(apps, schema_editor):
    FinancialYear = apps.get_model('mi', 'FinancialYear')
    FinancialYear(id=2016, description="2016-17").save()


class Migration(migrations.Migration):

    dependencies = [
        ('mi', '0029_auto_20170329_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.RunPython(do_thing),
    ]
