# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-30 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi', '0030_auto_20170329_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='hvc_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='mi.HVCGroup'),
        ),
        migrations.AddField(
            model_name='target',
            name='financial_year',
            field=models.ForeignKey(default=2016, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='mi.FinancialYear'),
            preserve_default=False,
        ),
    ]
