# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-03 15:15
from __future__ import unicode_literals

from django.db import migrations

def add_financial_years(apps, schema_editor):
    FinancialYear = apps.get_model('mi', 'FinancialYear')
    FinancialYear(id=2016, description="2016-17").save()
    FinancialYear(id=2017, description="2017-18").save()


def update_2016_targets_fy(apps, schema_editor):
    Target = apps.get_model('mi', 'Target')
    FinancialYear = apps.get_model('mi', 'FinancialYear')
    for target in Target.objects.all():
        target.financial_year = FinancialYear.objects.get(id=2016)
        target.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mi', '0030_auto_20170403_1338'),
    ]

    operations = [
        migrations.RunPython(add_financial_years),
        migrations.RunPython(update_2016_targets_fy),
    ]
