# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-08 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi', '0032_auto_20170403_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='parent_sector',
        ),
        migrations.AddField(
            model_name='sector',
            name='parent_sector',
            field=models.ManyToManyField(related_name='sectors', to='mi.ParentSector'),
        ),
        migrations.RemoveField(
            model_name='sector',
            name='sector_team',
        ),
        migrations.AddField(
            model_name='sector',
            name='sector_team',
            field=models.ManyToManyField(related_name='sectors', to='mi.SectorTeam'),
        ),
    ]
