# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-13 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi', '0032_auto_20170403_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='hvc_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='mi.HVCGroup'),
        ),
    ]
