# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-05 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi', '0035_auto_20170511_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverseasRegionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='OverseasRegionYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi.Country')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi.FinancialYear')),
                ('overseas_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi.OverseasRegion')),
            ],
        ),
        migrations.AlterField(
            model_name='target',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targets', to='mi.Country'),
        ),
        migrations.AlterField(
            model_name='target',
            name='hvc_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='mi.HVCGroup'),
        ),
        migrations.AddField(
            model_name='country',
            name='overseas_region_new',
            field=models.ManyToManyField(related_name='countries_new', through='mi.OverseasRegionYear', to='mi.OverseasRegion'),
        ),
        migrations.AddField(
            model_name='overseasregion',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='mi.OverseasRegionGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='overseasregionyear',
            unique_together=set([('financial_year', 'country')]),
        ),
    ]
