# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-05 16:26
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    OverseasRegion = apps.get_model('mi', 'OverseasRegion')
    OverseasRegionYear = apps.get_model('mi', 'OverseasRegionYear')
    Country = apps.get_model('mi', 'Country')
    FinancialYear = apps.get_model('mi', 'FinancialYear')

    fy2016 = FinancialYear.objects.get(id='2016')
    fy2017 = FinancialYear.objects.get(id='2017')
    to_create = []

    # bake in 2016/17 data

    data2016_17 = {
        'Australia-New Zealand': [
            {'country': 'AU'}, {'country': 'SB'}, {'country': 'NF'}, {'country': 'CC'},
            {'country': 'VU'}, {'country': 'WS'}, {'country': 'TO'}, {'country': 'FM'},
            {'country': 'CK'}, {'country': 'NR'}, {'country': 'CX'}, {'country': 'FJ'},
            {'country': 'NU'}, {'country': 'TK'}, {'country': 'NZ'}, {'country': 'PG'},
            {'country': 'PW'}, {'country': 'PN'}, {'country': 'MH'}, {'country': 'KI'},
            {'country': 'HM'}, {'country': 'TV'}
        ],
        'Central European Network': [
            {'country': 'HR'}, {'country': 'BA'}, {'country': 'AT'}, {'country': 'ME'}, {'country': 'AL'},
            {'country': 'HU'}, {'country': 'RS'}, {'country': 'SI'}, {'country': 'SK'}, {'country': 'RO'},
            {'country': 'CZ'}, {'country': 'MD'}, {'country': 'MK'}, {'country': 'BG'}, {'country': 'PL'}
        ],
        'China': [
            {'country': 'CN'}, {'country': 'MO'}, {'country': 'HK'}
        ],
        'East Africa': [
            {'country': 'SO'}, {'country': 'SS'}, {'country': 'KE'}, {'country': 'ET'}, {'country': 'DJ'},
            {'country': 'RW'}, {'country': 'UG'}, {'country': 'ER'}, {'country': 'TZ'}, {'country': 'BI'}
        ],
        'Latin America': [
            {'country': 'HT'}, {'country': 'VE'}, {'country': 'GT'}, {'country': 'PA'}, {'country': 'MX'},
            {'country': 'AR'}, {'country': 'DO'}, {'country': 'PY'}, {'country': 'CU'}, {'country': 'NI'},
            {'country': 'UY'}, {'country': 'CL'}, {'country': 'HN'}, {'country': 'SR'}, {'country': 'EC'},
            {'country': 'BR'}, {'country': 'SV'}, {'country': 'BO'}, {'country': 'CO'}, {'country': 'PE'},
            {'country': 'CR'}
        ],
        'Mediterranean': [
            {'country': 'VA'}, {'country': 'MT'}, {'country': 'ES'}, {'country': 'PT'}, {'country': 'GI'},
            {'country': 'SM'}, {'country': 'IL'}, {'country': 'IT'}, {'country': 'CY'}, {'country': 'MC'},
            {'country': 'GR'}
        ],
        'Middle East': [
            {'country': 'OM'}, {'country': 'AE'}, {'country': 'JO'}, {'country': 'YE'}, {'country': 'SA'},
            {'country': 'BH'}, {'country': 'LB'}, {'country': 'PK'}, {'country': 'PS'}, {'country': 'IQ'},
            {'country': 'SY'}, {'country': 'AF'}, {'country': 'IR'}, {'country': 'KW'}, {'country': 'QA'}
        ],
        'Nordic Baltic Network': [
            {'country': 'LT'}, {'country': 'NO'}, {'country': 'FI'}, {'country': 'BV'}, {'country': 'GL'},
            {'country': 'SJ'}, {'country': 'EE'}, {'country': 'DK'}, {'country': 'IS'}, {'country': 'SE'},
            {'country': 'AX'}, {'country': 'LV'}, {'country': 'FO'}
        ],
        'North Africa': [
            {'country': 'TN'}, {'country': 'DZ'}, {'country': 'LY'}, {'country': 'SD'}, {'country': 'EH'},
            {'country': 'EG'}, {'country': 'MA'}, {'country': 'MR'}
        ],
        'North America': [
            {'country': 'TT'}, {'country': 'BS'}, {'country': 'VC'}, {'country': 'BZ'}, {'country': 'LC'},
            {'country': 'VG'}, {'country': 'FK'}, {'country': 'AS'}, {'country': 'VI'}, {'country': 'BM'},
            {'country': 'TC'}, {'country': 'PR'}, {'country': 'AG'}, {'country': 'MS'}, {'country': 'UM'},
            {'country': 'US'}, {'country': 'KY'}, {'country': 'KN'}, {'country': 'BB'}, {'country': 'GY'},
            {'country': 'DM'}, {'country': 'AI'}, {'country': 'GD'}, {'country': 'SH'}, {'country': 'CA'},
            {'country': 'JM'}, {'country': 'GS'}, {'country': 'AQ'}, {'country': 'MP'}, {'country': 'GU'}
        ],
        'North East Asia': [
            {'country': 'MN'}, {'country': 'KR'}, {'country': 'TW'}, {'country': 'JP'}, {'country': 'KP'}
        ],
        'South Asia': [
            {'country': 'BD'}, {'country': 'IN'}, {'country': 'BT'}, {'country': 'LK'}, {'country': 'NP'}, {'country': 'MV'}
        ],
        'South East Asia': [
            {'country': 'MY'}, {'country': 'PH'}, {'country': 'LA'}, {'country': 'TL'}, {'country': 'TH'},
            {'country': 'VN'}, {'country': 'IO'}, {'country': 'BN'}, {'country': 'ID'}, {'country': 'SG'},
            {'country': 'KH'}, {'country': 'MM'}
        ],
        'Southern Africa': [
            {'country': 'MW'}, {'country': 'SZ'}, {'country': 'BW'}, {'country': 'MZ'}, {'country': 'ZA'},
            {'country': 'ZW'}, {'country': 'MU'}, {'country': 'AO'}, {'country': 'LS'}, {'country': 'KM'},
            {'country': 'ZM'}, {'country': 'MG'}, {'country': 'NA'}, {'country': 'SC'}
        ],
        'Turkey and Caucasus': [
            {'country': 'KZ'}, {'country': 'UA'}, {'country': 'AZ'}, {'country': 'UZ'}, {'country': 'GE'},
            {'country': 'TM'}, {'country': 'BY'}, {'country': 'TR'}, {'country': 'KG'}, {'country': 'AM'},
            {'country': 'TJ'}, {'country': 'RU'}
        ],
        'West Africa': [
            {'country': 'SL'}, {'country': 'LR'}, {'country': 'CF'}, {'country': 'BF'}, {'country': 'GM'},
            {'country': 'ST'}, {'country': 'CI'}, {'country': 'CM'}, {'country': 'CV'}, {'country': 'GH'},
            {'country': 'SN'}, {'country': 'GA'}, {'country': 'GN'}, {'country': 'BJ'}, {'country': 'NE'},
            {'country': 'GQ'}, {'country': 'ML'}, {'country': 'TG'}, {'country': 'CD'}, {'country': 'NG'},
            {'country': 'CG'}, {'country': 'TD'}, {'country': 'GW'}
        ],
        'Western Europe': [
            {'country': 'PM'}, {'country': 'PF'}, {'country': 'DE'}, {'country': 'LI'}, {'country': 'MQ'},
            {'country': 'GP'}, {'country': 'YT'}, {'country': 'GF'}, {'country': 'AD'}, {'country': 'CW'},
            {'country': 'AW'}, {'country': 'MF'}, {'country': 'TF'}, {'country': 'RE'}, {'country': 'WF'},
            {'country': 'FR'}, {'country': 'SX'}, {'country': 'LU'}, {'country': 'NC'}, {'country': 'BQ'},
            {'country': 'CH'}, {'country': 'BL'}, {'country': 'IE'}, {'country': 'BE'}, {'country': 'NL'}
        ]
    }

    data2017_18 = {
        'Africa': [
            'AO', 'BJ', 'BW', 'BF', 'BI', 'CV', 'CM', 'CF', 'TD', 'KM', 'CG', 'CD', 'CI', 'DJ', 'GQ', 'ER', 'ET', 'GA',
            'GM', 'GH', 'GN', 'GW', 'KE', 'LS', 'LR', 'MG', 'MW', 'ML', 'MU', 'MZ', 'NA', 'NE', 'NG', 'RW', 'ST', 'SN',
            'SC', 'SL', 'SO', 'ZA', 'SS', 'SZ', 'TZ', 'TG', 'UG', 'ZM', 'ZW'
        ],
        'Australia-New Zealand': [
            'AU', 'CX', 'CC', 'CK', 'FJ', 'HM', 'KI', 'MH', 'FM', 'NR', 'NZ', 'NU', 'NF', 'PW', 'PG', 'PN', 'WS', 'SB',
            'TK', 'TO', 'TV', 'VU'
        ],
        'Central European Network': [
            'AL', 'BA', 'BG', 'HR', 'CZ', 'HU', 'XK', 'MK', 'MD', 'ME', 'PL', 'RO', 'RS', 'SK', 'SI'
        ],
        'China': ['CN', 'HK', 'MO'],
        'Latin America': [
            'AI', 'AG', 'AR', 'BS', 'BB', 'BZ', 'BM', 'BO', 'BR', 'KY', 'CL', 'CO', 'CR', 'CU', 'DM', 'DO', 'EC', 'SV',
            'FK', 'GD', 'GT', 'GY', 'HT', 'HN', 'JM', 'MX', 'MS', 'NI', 'PA', 'PY', 'PE', 'SH', 'KN', 'LC', 'VC', 'GS',
            'SR', 'TT', 'TC', 'UY', 'VE', 'VG'
        ],
        'Mediterranean': ['AD', 'CY', 'GI', 'GR', 'VA', 'IL', 'IT', 'MT', 'PT', 'SM', 'ES'],
        'Middle East': ['AF', 'BH', 'IR', 'IQ', 'JO', 'KW', 'LB', 'OM', 'PK', 'PS', 'QA', 'SA', 'SY', 'AE', 'YE'],
        'Nordic Baltic Network': ['AX', 'BV', 'DK', 'EE', 'FO', 'FI', 'GL', 'IS', 'LV', 'LT', 'NO', 'SJ', 'SE'],
        'North Africa': ['DZ', 'EG', 'LY', 'MR', 'MA', 'SD', 'TN', 'EH'],
        'North America': ['AS', 'CA', 'GU', 'MP', 'PR', 'UM', 'US', 'VI'],
        'North East Asia': ['JP', 'KP', 'KR', 'TW'],
        'South Asia': ['BD', 'BT', 'IN', 'MV', 'NP', 'LK'],
        'South East Asia': ['IO', 'BN', 'KH', 'ID', 'LA', 'MY', 'MM', 'PH', 'SG', 'TH', 'TL', 'VN'],
        'Turkey and Caucasus': ['AM', 'AZ', 'BY', 'GE', 'KZ', 'KG', 'MN', 'RU', 'TJ', 'TR', 'TM', 'UA', 'UZ'],
        'Western Europe': [
            'AQ', 'AW', 'AT', 'BE', 'BQ', 'CW', 'FR', 'GF', 'PF', 'TF', 'DE', 'GP', 'GG', 'IE', 'IM', 'JE', 'LI', 'LU',
            'MQ', 'YT', 'MC', 'NL', 'NC', 'RE', 'BL', 'MF', 'PM', 'SX', 'CH', 'WF'
        ]
    }

    for region, countries in data2016_17.items():
        oregion = OverseasRegion.objects.get(name=region)
        for country in countries:
            to_create.append(
                OverseasRegionYear(
                    financial_year=fy2016,
                    country=Country.objects.get(country=country['country']),
                    overseas_region=oregion)
            )

    for region, countries in data2017_18.items():
        oregion, _ = OverseasRegion.objects.get_or_create(name=region)
        for country_code in countries:
            try:
                country = Country.objects.get(country=country_code)
            except Country.DoesNotExist:
                country = Country(country=country_code, overseas_region=oregion)
                country.save()

            to_create.append(
                OverseasRegionYear(
                    financial_year=fy2017,
                    country=country,
                    overseas_region=oregion
                )
            )
    OverseasRegionYear.objects.bulk_create(to_create)


class Migration(migrations.Migration):
    dependencies = [
        ('mi', '0036_auto_20170605_1635'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
