# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi', '0037_auto_20170605_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='overseas_region',
        ),
        migrations.RemoveField(
            model_name='country',
            name='overseas_region_new',
        ),
        migrations.AddField(
            model_name='country',
            name='overseas_regions',
            field=models.ManyToManyField(related_name='countries', through='mi.OverseasRegionYear', to='mi.OverseasRegion'),
        ),
        migrations.AlterField(
            model_name='target',
            name='hvc_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='mi.HVCGroup'),
        ),
    ]
