# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi', '0038_auto_20170608_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverseasRegionGroupYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi.FinancialYear')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi.OverseasRegionGroup')),
            ],
        ),
        migrations.RemoveField(
            model_name='overseasregion',
            name='group',
        ),
        migrations.AlterField(
            model_name='target',
            name='hvc_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='mi.HVCGroup'),
        ),
        migrations.AddField(
            model_name='overseasregiongroupyear',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi.OverseasRegion'),
        ),
        migrations.AddField(
            model_name='overseasregiongroup',
            name='regions',
            field=models.ManyToManyField(through='mi.OverseasRegionGroupYear', to='mi.OverseasRegion'),
        ),
    ]
