# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi', '0038_auto_20170612_1255'),
        ('mi', '0040_auto_20170612_1012'),
    ]

    operations = [
    ]
