# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 14:46
from __future__ import unicode_literals

from django.db import migrations


def add_2017_hvc_global(apps, schema_editor):
    Country = apps.get_model('mi', 'Country')
    Target = apps.get_model('mi', 'Target')
    FinancialYear = apps.get_model('mi', 'FinancialYear')
    global_country, _ = Country.objects.get_or_create(country='XG')
    hvc_2017 = ['E225', 'E224']
    financial_year = FinancialYear.objects.get(id=2017)
    for hvc in hvc_2017:
        if Target.objects.filter(campaign_id=hvc, financial_year=financial_year).exists():
            target = Target.objects.get(campaign_id=hvc, financial_year=financial_year)
            target.country.add(global_country)
            target.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mi', '0042_auto_20170614_1114'),
    ]

    operations = [
        migrations.RunPython(add_2017_hvc_global, migrations.RunPython.noop),
    ]

