# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 10:11
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion

from wins.constants import UK_REGIONS


class Migration(migrations.Migration):

    dependencies = [
        ('mi', '0043_auto_20170707_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='UKRegionTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_exporters', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=12)),
                ('sustainable', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=12)),
                ('growth', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(default=0), size=12)),
                ('region', models.PositiveSmallIntegerField(choices=[(1, 'East Midlands'), (2, 'East of England'), (3, 'London'), (4, 'North East'), (5, 'North West'), (6, 'Northern Ireland'), (7, 'Scotland'), (8, 'South East'), (9, 'South West'), (10, 'Wales'), (11, 'West Midlands'), (12, 'Yorkshire and The Humber')])),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_targets', to='mi.FinancialYear')),
            ],
        ),
        migrations.AlterField(
            model_name='target',
            name='hvc_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='mi.HVCGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='ukregiontarget',
            unique_together=set([('financial_year', 'region')]),
        ),
    ]

