# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi', '0045_auto_20170905_1606'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.CreateModel(
                name='TargetCountry',
                fields=[
                    ('id', models.AutoField(auto_created=True,
                                            primary_key=True, serialize=False, verbose_name='ID')),
                    ('country', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='mi.Country')),
                ],
                options={
                    'db_table': 'mi_target_country',
                },
            ),
            migrations.AlterField(
                model_name='target',
                name='country',
                field=models.ManyToManyField(
                    related_name='targets', through='mi.TargetCountry', to='mi.Country'),
            ),
            migrations.AddField(
                model_name='targetcountry',
                name='target',
                field=models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='mi.Target'),
            ),
            migrations.AlterUniqueTogether(
                name='targetcountry',
                unique_together=set([('target', 'country')]),
            ),
        ]),
    ]
