# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 15:48
from __future__ import unicode_literals

from django.db import migrations


def add_mid_year_changes_2017_18(apps, schema_editor):
    Country = apps.get_model('mi', 'Country')
    Target = apps.get_model('mi', 'Target')
    FinancialYear = apps.get_model('mi', 'FinancialYear')
    TargetCountry = apps.get_model('mi', 'TargetCountry')

    # E020 has had FI included as a secondary market
    financial_year_17 = FinancialYear.objects.get(id=2017)
    if Target.objects.filter(campaign_id='E020', financial_year=financial_year_17).exists():
        target = Target.objects.get(
            campaign_id='E020', financial_year=financial_year_17)
        country_code = 'FI'
        country = Country.objects.get(country=country_code)
        TargetCountry(target=target, country=country).save()

    # associate E242 with SN as primary market and MR as secondary
    if Target.objects.filter(campaign_id='E242', financial_year=financial_year_17).exists():
        target = Target.objects.get(
            campaign_id='E242', financial_year=financial_year_17)
        primary = Country.objects.get(country='SN')
        TargetCountry(target=target, country=primary,
                      contributes_to_target=True).save()

        secondary = Country.objects.get(country='MR')
        TargetCountry(target=target, country=secondary).save()


class Migration(migrations.Migration):

    dependencies = [
        ('mi', '0049_auto_20171101_1436'),
    ]

    operations = [
        migrations.RunPython(add_mid_year_changes_2017_18),
    ]
