# Generated by Django 2.0.13 on 2019-09-20 13:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi', '0051_auto_20180117_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='ukregiontarget',
            name='unknown',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], size=12),
            preserve_default=False,
        ),
    ]
