# Generated by Django 2.0.8 on 2018-11-02 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi', '0051_auto_20180117_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='hvc_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='mi.HVCGroup'),
        ),
    ]
