
# Depending on how often these are edited, it may make more sense to put these
# into a model of their own, but as I don't have that information handy, I'm
# not going to over-complicate things at this stage for the sake of
# over-engineering.
from extended_choices import Choices

from core.utils import TrackedSupersetChoices

EXPERIENCE = (
    (1, "We had not started exporting before this win"),
    (2, "Apart from this win, we have exported in the last 12 months"),
    (3, "We last exported 1 to 2 years ago"),
    (4, "2 to 5 years ago"),
    (5, "5 to 10 years ago"),
    (6, "More than 10 years ago"),
)

GOODS_VS_SERVICES = (
    (1, "Goods"),
    (2, "Services"),
    (3, "Both goods and services"),
)

HVO_PROGRAMMES = (
    ("AER-01", "AER-01: Global Aerospace"),
    ("AFB-01", "AFB-01: Aid Funded Business Service"),
    ("AUS-05", "AUS-05: Australian Roads"),
    ("AUS-06", "AUS-06: Australia Airports"),
    ("AZE-01", "AZE-01: Azerbaijan Oil & Gas"),
    ("BHR-01", "BHR-01: Bahrain Rail"),
    ("BRA-16", "BRA-16: Shipyard & Shipbuilding Programme"),
    ("BRA-18", "BRA-18: Petrobras Business Plan 2013 - 2017"),
    ("BRA-42", "BRA-42: PPP Healthcare Programme"),
    ("BRA-43", "BRA-43: Brazilian Sports Infrastructure"),
    ("BRA-44", "BRA-44: Integrated Logistics"),
    ("BRA-45", "BRA-45: Brazilian Education"),
    ("BSC-01", "BSC-01: Big Science"),
    ("BSC-02", "BSC-02: ITER - Big Science Nuclear Fusion Project"),
    ("BWA-01", "BWA-01: Botswana Mining"),
    ("CAN-01", "CAN-01: Toronto Rail"),
    ("CHL-12", "CHL-12: Chile Mining"),
    ("CHN-14", "CHN-14: China Healthcare"),
    ("CHN-20", "CHN-20: China New Energy (Renewables)"),
    ("CHN-21", "CHN-21: China New Energy (Nuclear)"),
    ("CHN-49", "CHN-49: China Built Environment"),
    ("CHN-51", "CHN-51: China Airports"),
    ("CHN-53", "CHN-53: Chinese Commercial Aircraft Programmes"),
    ("CHN-54", "CHN-54: Clean and Energy Efficient Production"),
    ("CHN-55", "CHN-55: Technology Giants in China"),
    ("CHN-56", "CHN-56: China Education"),
    ("CHN-57", "CHN-57: China Maritime"),
    ("COL-02", "COL-02: Colombia Municipal infrastructure projects"),
    ("COL-03", "COL-03: Colombia Multiple transport projects"),
    ("COL-04", "COL-04: Colombian Education"),
    ("COL-05", "COL-05: Colombia Mining"),
    ("DNK-06", "DNK-06: Femern Link Project"),
    ("DZA-01", "DZA-01: Algeria Healthcare"),
    ("EAF-02", "EAF-02: Kenya-Ethiopia Transport Corridor"),
    ("EAK-01", "EAK-01: Kenya Gas"),
    ("EDU-01", "EDU-01: Education"),
    ("EDU-02", "EDU-02: International Curriculum Schools"),
    ("EDU-03", "EDU-03: ASEAN Education & Training"),
    ("EGY-01", "EGY-01: Suez Canal Regional Development Project"),
    ("ETH-01", "ETH-01: Transport Corridor"),
    ("EUR-02", "EUR-02: Northern Europe Offshore Wind & Interconnector projects"),
    ("FRA-01", "FRA-01: Big Science"),
    ("GIN-01", "GIN-01: Guinea Mining"),
    ("GSC-01", "GSC-01: Global Smart Cities"),
    ("HJK-01", "HJK-01: Jordan Nuclear New Build"),
    ("HKG-01", "HKG-01: Hong Kong Integrated Transport"),
    ("HKG-05", "HKG-05: Kai Tak Development"),
    ("HKG-08", "HKG-08: West Kowloon Cultural District"),
    ("HKG-09", "HKG-09: Zhuhai-Macao Bridge & Related Projects"),
    ("HKG-15", "HKG-15: Hong Kong Airport"),
    ("HKG-16", "HKG-16: Hong Kong Environment"),
    ("HKG-17", "HKG-17: Hong Kong Hospitals"),
    ("HKG-18", "HKG-18: Hong Kong Urban Regeneration & Built Heritage"),
    ("INA-01", "INA-01: Indonesia Infrastructure"),
    ("INA-04", "INA-04: Indonesia Aerospace"),
    ("IND-03", "IND-03: Indian metro opportunities"),
    ("IND-31", "IND-31: Conventional Power and Renewables"),
    ("IND-32", "IND-32: Civil Nuclear"),
    ("IND-50", "IND-50: Indian Industrial Corridors"),
    ("IND-51", "IND-51: India Healthcare"),
    ("IRQ-10", "IRQ-10: Iraq Oil & Gas"),
    ("IRQ-11", "IRQ-11: Iraq Federal Water Projects"),
    ("JPN-07", "JPN-07: Fukushima Decommissioning"),
    ("JPN-08", "JPN-08: Japan - Major Sporting Events"),
    ("KAZ-07", "KAZ-07: Kazakhstan Mining"),
    ("KAZ-02", "KAZ-02: Multiple Oil & Gas Projects"),
    ("KAZ-03", "KAZ-03: Kazakhstan Infrastructure"),
    ("KAZ-06", "KAZ-06: Kazakhstan Education and Training"),
    ("KOR-05", "KOR-05: Global Sports Projects in Korea"),
    ("KWT-01", "KWT-01: Kuwait Airport Redevelopment"),
    ("KWT-02", "KWT-02: Boubyan Island Development"),
    ("KWT-03", "KWT-03: New Hospitals Project"),
    ("KWT-04", "KWT-04: Kuwait Metro System"),
    ("LBY-01", "LBY-01: Libya Infrastructure"),
    ("LBY-02", "LBY-02: Libya Healthcare"),
    ("LBY-03", "LBY-03: Libya Water"),
    ("LBY-04", "LBY-04: Libya Airports"),
    ("MAC-01", "MAC-01: Macau Retail & Leisure"),
    ("MEX-04", "MEX-04: Mexico Oil and Gas"),
    ("MEX-05", "MEX-05: Mexican Education"),
    ("MEX-07", "MEX-07: Veracruz Port Expansion"),
    ("MEX-08", "MEX-08: Mexico Airports"),
    ("MIN-01", "MIN-01: Global Mining Supply Chains"),
    ("MIN-02", "MIN-02: Energy for the West African Mining Industry (West African Power Pool/WAPP)"),
    ("MNG-01", "MNG-01: Mongolia Mining"),
    ("MOR-01", "MOR-01: Morocco Mining"),
    ("MOZ-01", "MOZ-01: Mozambique Gas"),
    ("MYS-06", "MYS-06: Malaysian Transport Projects"),
    ("MYS-07", "MYS-07: Malaysia Education"),
    ("NGA-05", "NGA-05: Nigeria Oil & Gas projects"),
    ("NOR-01", "NOR-01: Oil & Gas Norway"),
    ("NUC-01", "NUC-01: Central European Nuclear"),
    ("NUC-04", "NUC-04: Nuclear Vendor Strategy"),
    ("NUC-05", "NUC-05: Western Europe Decommissioning"),
    ("NZL-01", "NZL-01: Christchurch Reconstruction"),
    ("OAG-01", "OAG-01: East Africa Oil & Gas"),
    ("OMN-01", "OMN-01: Omani Railway Network"),
    ("OMN-05", "OMN-05: OMAN Healthcare"),
    ("OTH-11", "OTH-11: Aid Funded Business Service"),
    ("OTH-12", "OTH-12: Building Creative Hubs Internationally"),
    ("OTH-13", "OTH-13: Creative Industries HVO Taskforce"),
    ("OTH-14", "OTH-14: Creative Tax Credits"),
    ("OTH-15", "OTH-15: Food and Drink Export Action Plan"),
    ("OTH-16", "OTH-16: Free Trade Agreements"),
    ("OTH-18", "OTH-18: Global E Retail (Digital Export Growth) Programme"),
    ("OTH-22", "OTH-22: UK Retail Industry - International Action Plan"),
    ("PAN-01", "PAN-01: Panama Canal Megaprojects"),
    ("PAN-02", "PAN-02: Panama City Metro Lines 2 and 3"),
    ("PER-01", "PER-01: Peru Mass Rapid Transport System"),
    ("PER-03", "PER-03: Peru Mining"),
    ("PER-04", "PER-04: Lima 2019 Pan-American Games"),
    ("PHL-09", "PHL-09: PPP Infrastructure Projects"),
    ("POL-01", "POL-01: Polish Rail"),
    ("QAT-04", "QAT-04: Qatari Rail Network"),
    ("QAT-06", "QAT-06: World Cup 2022"),
    ("QAT-07", "QAT-07: Qatari National Food Security Programme"),
    ("QAT-08", "QAT-08: Qatar Education and Training"),
    ("REN-01", "REN-01: Northern Europe Offshore Wind & Interconnector Projects"),
    ("RUS-50", "RUS-50: Russian Sports Infrastructure Projects"),
    ("RUS-52", "RUS-52: Russia Oil"),
    ("RUS-54", "RUS-54: Russia Experience Economy"),
    ("SAU-06", "SAU-06: Saudi Railways Development Programme"),
    ("SAU-08", "SAU-08: Healthcare Development Programme"),
    ("SAU-15", "SAU-15: Saudi Airport Developments"),
    ("SAU-17", "SAU-17: Saudi Water Projects"),
    ("SAU-19", "SAU-19: Saudi Arabia Oil & Gas"),
    ("SAU-20", "SAU-20: Saudi Nuclear - New Build"),
    ("SAU-21", "SAU-21: Saudi Education"),
    ("SAU-22", "SAU-22: Jeddah Urban Redevelopment Programme"),
    ("SGP-06", "SGP-06: Mass Rapid Transport"),
    ("SGP-07", "SGP-07: Changi Airport"),
    ("SGP-08", "SGP-08: Singapore Water"),
    ("SPO-01", "SPO-01: Central Asia Major Sports Events"),
    ("SSA-01", "SSA-01: Angola Oil & Gas"),
    ("TGA-01", "TGA-01: Technology Giants in SE Asia"),
    ("TGU-01", "TGU-01: Technology Giants in the USA"),
    ("THA-01", "THA-01: Flood Management & Transport Infrastructure"),
    ("THA-10", "THA-10: Thailand Rail & Airport"),
    ("TUR-26", "TUR-26: Turkey Nuclear New Build"),
    ("TUR-27", "TUR-27: Istanbul Airport"),
    ("TUR-28", "TUR-28: PPP & Healthcare"),
    ("TWN-15", "TWN-15: Rail Projects"),
    ("TWN-19", "TWN-19: Taiwan Renewables"),
    ("TWN-20", "TWN-20: Taiwan Nuclear"),
    ("TZA-01", "TZA-01: Tanzania Gas"),
    ("UAE-04", "UAE-04: UAE Rail Project"),
    ("UAE-05", "UAE-05: UAE Experience Economy"),
    ("UAE-12", "UAE-12: UAE Healthcare"),
    ("UAE-13", "UAE-13: UAE Expo 2020"),
    ("UAE-19", "UAE-19: Dubai Airport Expansion"),
    ("UAE-21", "UAE-21: Water"),
    ("UAE-20", "UAE-20: UAE Education"),
    ("UAE-27", "UAE-27 "),
    ("UGA-01", "UGA-01: Uganda Gas"),
    ("UKR-01", "UKR-01: Ukraine Aerospace"),
    ("USA-26", "USA-26: US Water Sector Capital Improvement Program/Plan"),
    ("USA-31", "USA-31: US Infrastructure"),
    ("USA-32", "USA-32: North American Aircraft Programmes"),
    ("VNM-30", "VNM-30: Vietnam Urban Regeneration and Transport Projects"),
    ("VNM-31", "VNM-31: Vietnam Nuclear New Build"),
)


PROGRAMMES = TrackedSupersetChoices(
    ('AFTERBURNER', 1, "Afterburner"),
    ('AFBS', 2, "Aid Funded Business Service (AFBS)"),
    ('BOFB', 3, "Britain Open for Business"),
    ('BBN', 4, "British Business Network"),
    ('BDS_US', 5, "British Defence Staff - US"),
    ('BWFCOI', 6, "Business Win FCO Involvement"),
    ('CMA', 7, "Catalyst Members Activities"),
    ('CENAE', 8, "CEN Adv Engineering"),
    ('CENAM', 9, "CEN Adv Manufacturing"),
    ('CENDS', 10, "CEN Defence & Security"),
    ('CENE', 11, "CEN Energy"),
    ('CENHLS', 12, "CEN Health & Life Science"),
    ('CENI', 13, "CEN Infrastructure"),
    ('CENLS', 14, "CEN Life Science"),
    ('CNESEC', 15, "CEN Security"),
    ('CENSER', 16, "CEN Services"),
    ('CG', 17, "Commonwealth Games"),
    ('CAM', 94, "Communication and Marketing"),
    ('DOF', 92, "Design our future"),
    ('DTA', 18, "Digital Trade Advisor"),
    ('EXPORTING', 19, "E-Exporting"),
    ('EIGR', 87, "EiG Referral"),
    ('EMACCE', 20, "Emerging Markets Contract (CEE)"),
    ('EMCG', 21, "Emerging Markets Contract (Gulf)"),
    ('EMCLA', 22, "Emerging Markets Contract (LA)"),
    ('EMCR', 23, "Emerging Markets Contract (Russia)"),
    ('EA', 24, "Events Alliance"),
    ('EXBEI', 88, "Expo 2019 Beijing"),
    ('ECR', 25, "Export Communication Review Scheme (ECR)"),
    ('EGS', 26, "Export Growth Service"),
    ('EO', 72, "Export Opportunities"),
    ('EOFXI', 27, "Export Oriented FDI"),
    ('EIG', 28, "Exporting is GREAT (EiG)"),
    ('EYSBW', 29, "EY Specialist Business Win"),
    ('FTEP', 30, "First Time Exporters Programme"),
    ('FTAS', 31, "Free Trade Agreements"),
    ('GCP', 32, "GCP"),
    ('GCPDELOITEE', 33, "GCP - Deloitte"),
    ('GCPEY', 34, "GCP - EY"),
    ('GCPHSBC', 35, "GCP - HSBC"),
    ('GCPKPMG', 36, "GCP - KPMG"),
    ('GCPLLOYDS', 37, "GCP - Lloyds"),
    ('GCPPWC', 38, "GCP - PwC"),
    ('GCPRBS', 39, "GCP - RBS"),
    ('GCPSANTANDER', 40, "GCP - Santander"),
    ('GCPSC', 41, "GCP - Standard Chartered"),
    ('GEP', 90, "Global Entrepreneur Programme (GEP)"),
    ('GGP', 83, "Global Growth Pilot"),
    ('GBEGC', 42, "GREAT Branded Event Great Campaign"),
    ('GBHR', 71, "GREAT British House Rio"),
    ('GCF', 43, "GREAT Challenge Fund"),
    ('FIG', 91, "GREAT Food is GREAT"),
    ('GFA', 44, "GREAT Funded Activity"),
    ('GW', 45, "GREAT Weeks"),
    ('GIBGBP', 46, "Grown in Britain Global Business Programme"),
    ('HAIC', 89, "HAIC - Healthcare Artificial Intelligence Catalyst"),
    ('HVOSI', 47, "HVO Specialist [involvement]"),
    ('IIIDTS', 48, "III - Deal Ticket Size"),
    ('IP', 49, "Innovation Programme"),
    ('IFB', 50, "International Festival for Business"),
    ('JETCO', 51, "JETCO"),
    ('LCI', 52, "Low Carbon Initiative"),
    ('LR', 53, "Luxury Retail"),
    ('ME', 73, "Midlands Engine"),
    ('ME2015', 54, "Milan Expo 2015"),
    ('MSBP', 55, "MSB Programme"),
    ('MEGS', 56, "Music Export Growth Scheme (MEGS)"),
    ('NPH', 57, "Northern Powerhouse (NPH)"),
    ('NPR', 84, "National Partner Referral"),
    ('OWIO', 58, "Offshore Wind Investment Organisation"),
    ('O2012', 59, "Olympics 2012"),
    ('OMIS', 60, "Overseas Market Introduction Service (OMIS)"),
    ('PASBW', 61, "PA Specialist Business Win"),
    ('P2E', 70, "Passport to Export (P2E)"),
    ('RAT', 93, "Red Arrows Tour 2019"),
    ('RUK', 62, "Reshore UK"),
    ('RWCBF', 63, "Rugby World Cup - Business Festival"),
    ('SL', 64, "Shakespeare Lives"),
    ('SS', 85, "Specialist Support"),
    ('SE', 65, "Stakeholder Engagement"),
    ('TAP', 86, "Tradeshow Access Programme"),
    ('TSB', 66, "Technology Strategy Board (TSB)"),
    ('UKILTH', 67, "UK Israel Tech Hub"),
    ('VC', 68, "Venture Capital"),
    ('WEBEP', 69, "Web-based Exporting Programme"),
    ('NA', 75, "Not applicable"),
    ('ASTANAEXPO', 76, "Astana Expo 2017"),
    ('DUBAIEXPO', 77, "Dubai Expo 2020"),
    ('GFEST', 78, "GREAT Festival of Innovation (GFEST)"),
    ('GITC', 79, "GREAT International Trade Campaign"),
    ('MIPIM', 80, "MIPIM 2018"),
    ('PROSP', 81, "Prosperity Fund"),
    ('TE', 82, "PM Trade Envoy"),
    ('FINTECH', 95, "FinTech"),
    ('GBFS', 96, "Great British Food Showcase 2019"),
)

# Note: The programmes appear in the front end in the order they are listed here
PROGRAMMES.add_subset('ACTIVE', [
    'NA',
    'AFTERBURNER',
    'AFBS',
    'ASTANAEXPO',
    'BBN',
    'BDS_US',
    'BWFCOI',
    'CENAM',
    'CENDS',
    'CENHLS',
    'CENI',
    'CNESEC',
    'CENSER',
    'CG',
    'CAM',
    'DOF',
    'DTA',
    'DUBAIEXPO',
    'EXPORTING',
    'EIGR',
    'EMCG',
    'EMCLA',
    'EA',
    'EXBEI',
    'ECR',
    'EGS',
    'EO',
    'EOFXI',
    'EIG',
    'FINTECH',
    'FTEP',
    'FTAS',
    'GCPRBS',
    'GCPSANTANDER',
    'GBFS',
    'GCF',
    'GEP',
    'GGP',
    'FIG',
    'GFA',
    'GFEST',
    'GITC',
    'GIBGBP',
    'HAIC',
    'IP',
    'IFB',
    'JETCO',
    'LR',
    'MIPIM',
    'ME',
    'ME2015',
    'MSBP',
    'NPH',
    'NPR',
    'OWIO',
    'OMIS',
    'PROSP',
    'P2E',
    'RAT',
    'SL',
    'SE',
    'SS',
    'TAP',
    'TE',
    'WEBEP',
])

RATINGS = (
    (0, "N/A"),
    (1, "1"),
    (2, "2"),
    (3, "3"),
    (4, "4"),
    (5, "5"),
)


# these come from CDMS, except for those marked.
_SECTORS = (
    (1, "Advanced Engineering"),
    (2, "Aerospace"),
    (3, "Aerospace : Aircraft Design"),
    (4, "Aerospace : Component Manufacturing"),
    (5, "Aerospace : Component Manufacturing : Engines"),
    (6, "Aerospace : Component Manufacturing : test widgerts"),  # not cdms/spreadsheet
    (7, "Aerospace : Maintenance"),
    (8, "Aerospace : Manufacturing and Assembly"),
    (9, "Aerospace : Manufacturing and Assembly : Aircraft"),
    (10, "Aerospace : Manufacturing and Assembly : Helicopters"),
    (11, "Aerospace : Component Manufacturing : Space Technology"),
    (12, "Aerospace : Manufacturing and Assembly : Unmanned aerial vehicles"),
    (13, "Agriculture, horticulture, fisheries and pets"),
    (14, "Airports"),
    (15, "Automotive"),
    (16, "Automotive : Maintenance"),
    (17, "Automotive : Retail"),
    (18, "Automotive : Component Manufacturing"),
    (19, "Automotive : Component Manufacturing : Bodies and Coachwork"),
    (20, "Automotive : Component Manufacturing : Electronic Components"),
    (21, "Automotive : Component Manufacturing : Engines and Transmission"),
    (22, "Automotive : Component Manufacturing : Tyres"),
    (23, "Automotive : Design Engineering"),
    (24, "Automotive : Manufacturing and Assembly"),
    (25, "Automotive : Manufacturing and Assembly : Agricultural Machinery"),
    (26, "Automotive : Manufacturing and Assembly : Bicycles"),
    (27, "Automotive : Manufacturing and Assembly : Caravans"),
    (28, "Automotive : Manufacturing and Assembly : Cars"),
    (29, "Automotive : Manufacturing and Assembly : Containers"),
    (30, "Automotive : Manufacturing and Assembly : Invalid Carriages"),
    (31, "Automotive : Manufacturing and Assembly : Lorries"),
    (32, "Automotive : Manufacturing and Assembly : Motorcycles"),
    (33, "Automotive : Manufacturing and Assembly : Trailers"),
    (34, "Automotive : Manufacturing and Assembly : Vans"),
    (35, "Automotive : Motorsport"),
    (36, "Pharmaceuticals and biotechnology"),
    (37, "Pharmaceuticals and biotechnology : Marketing and Sales"),
    # (38, "Pharmaceuticals and biotechnology : Marketing and Sales : Bio and Pharma Retail"),
    # (39, "Pharmaceuticals and biotechnology : Marketing and Sales : Bio and Pharma Wholesale"),
    (40, "Pharmaceuticals and biotechnology : Biotechnology"),
    # (41, "Pharmaceuticals and biotechnology : Biotechnology : Agribio"),
    (42, "Pharmaceuticals and biotechnology : Biotechnology : Biodiagnostics"),
    # (43, "Pharmaceuticals and biotechnology : Biotechnology : Biomanufacturing"),
    # (44, "Pharmaceuticals and biotechnology : Biotechnology : Bioremediation"),
    # (45, "Pharmaceuticals and biotechnology : Biotechnology : Biotherapeutics"),
    # (46, "Pharmaceuticals and biotechnology : Biotechnology : Industrialbio"),
    # (47, "Pharmaceuticals and biotechnology : Biotechnology : Platform Technologies"),
    # (48, "Pharmaceuticals and biotechnology : Clinical Trials"),
    (49, "Pharmaceuticals and biotechnology : Professional services"),
    # (50, "Pharmaceuticals and biotechnology : Professional services : Contract Research"),
    # (51, "Pharmaceuticals and biotechnology : Professional services : Reagents, Consumables and
    # Instruments"),
    # (52, "Pharmaceuticals and biotechnology : Pharmaceuticals"),
    # (53, "Pharmaceuticals and biotechnology : Pharmaceuticals : Basic Pharmaceutical Products"),
    # (54, "Pharmaceuticals and biotechnology : Pharmaceuticals : Drug Discovery"),
    (55, "Pharmaceuticals and biotechnology : Manufacturing"),
    # (56, "Pharmaceuticals and biotechnology : Pharmaceuticals : Neutraceuticals"),
    # (57, "Pharmaceuticals and biotechnology : Vaccines"),
    (58, "Financial and Professional Services : Business and consumer services"),
    (59, "Financial and Professional Services : Business and consumer services : Commercial Real Estate Services"),
    (60, "Financial and Professional Services : Business and consumer services : Contact Centres"),
    (61, "Financial and Professional Services : Business and consumer services : HR Services"),
    (62, "Financial and Professional Services : Business and consumer services : Marketing Services"),
    (63, "Financial and Professional Services : Business and consumer services : Marketing Services : Market Research"),
    (64, "Financial and Professional Services : Business and consumer services : Shared Service Centres"),
    (65, "Chemicals"),
    (66, "Chemicals : Agricultural Chemicals"),
    (67, "Chemicals : Basic Chemicals"),
    (68, "Chemicals : Cleaning Preparations"),
    (69, "Chemicals : Miscellaneous Chemicals"),
    (70, "Chemicals : Paint, Coating and Adhesive Products"),
    (71, "Chemicals : Synthetic Materials"),
    (72, "Consumer and retail : Clothing, footwear and fashion"),
    #(73, "Consumer and retail : Clothing, Footwear and Fashion : Clothing"),
    #(74, "Consumer and retail : Clothing, Footwear and Fashion : Clothing : Workwear"),
    #(75, "Consumer and retail : Clothing, Footwear and Fashion : Footwear"),
    (76, "Technology and smart cities : Communications"),
    # (77, "Technology and smart cities : Communications : Broadband"),
    # (78, "Technology and smart cities : Communications : Communications Wholesale"),
    (79, "Technology and smart cities : Communications : Convergent"),
    (80, "Technology and smart cities : Communications : Fixed Line"),
    (81, "Technology and smart cities : Communications : Mobile"),
    # (82, "Technology and smart cities : Communications : Mobile : 3G Services"),
    # (83, "Technology and smart cities : Communications : Mobile : GSM"),
    # (84, "Technology and smart cities : Communications : Retail"),
    (85, "Technology and smart cities : Communications : Wireless"),
    # (86, "Technology and smart cities : Communications : Wireless : Wi-Fi"),
    # (87, "Technology and smart cities : Communications : Wireless : Wi-Max"),
    (88, "Construction"),
    (89, "Creative industries"),
    # (90, "Creative industries : Architecture"),
    (91, "Creative industries : Art"),
    # (92, "Creative industries : Art : Artistic and Literary Creation"),
    # (93, "Creative industries : Art : Arts Facilities Operation"),
    (94, "Creative industries : Design"),
    # (95, "Creative industries : Art : Fashion"),
    (96, "Creative industries : Performing arts"),
    # (97, "Creative industries : Film and tv"),
    (98, "Creative industries : Film and tv : Sales and distribution"),
    (99, "Creative industries : Equipment"),
    (100, "Creative industries : Equipment : Musical Instruments"),
    (101, "Creative industries : Equipment : Photo and Cinema"),
    # (102, "Creative industries : Creative industries Retail"),
    (103, "Creative industries : Antiques and Antiquities"),
    # (104, "Creative industries : Creative industries Retail : Art"),
    (105, "Creative industries : Books, printed media and stationery"),
    # (106, "Creative industries : Creative industries Wholesaling"),
    (107, "Creative industries : Multimedia Sales"),
    # (108, "Creative industries : Equipment : Musical Instruments"),
    # (109, "Creative industries : Creative industries Wholesaling : Photographic Goods"),
    (110, "Creative industries : Experience economy"),
    (111, "Creative industries : Digital media"),
    (112, "Creative industries : Advertising"),
    (113, "Creative industries : Equipment : Animation"),
    (114, "Creative industries : Music"),
    (115, "Creative industries : Publishing"),
    (116, "Creative industries : Film and tv"),
    (117, "Creative industries : Video Games"),
    # (118, "Creative industries : Media Reproduction"),
    # (119, "Creative industries : Media Reproduction : Printing"),
    # (120, "Creative industries : Media Reproduction : Reproduction"),
    (121, "Defence"),
    # (122, "Security"),
    (123, "Education and training"),
    (124, "Technology and smart cities : Hardware"),
    # (125, "Technology and smart cities : Hardware : Electronic Instruments"),
    # (126, "Technology and smart cities : Hardware : Electronics and IT Technologies"),
    # (127, "Technology and smart cities : Hardware : Electronics and IT Technologies :
    # Broadcasting"),
    # (128, "Technology and smart cities : Hardware : Electronics and IT Technologies : Component
    # Technologies"),
    # (129, "Technology and smart cities : Hardware : Electronics and IT Technologies : Computing"),
    # (130, "Technology and smart cities : Hardware : Electronics and IT Technologies : Display
    # Technologies"),
    # (131, "Technology and smart cities : Hardware : Electronics and IT Technologies : Network
    # Technologies"),
    # (132, "Technology and smart cities : Hardware : Electronics and IT Technologies : Security
    # Technologies"),
    (133, "Energy"),
    (134, "Environment"),
    (135, "Environment : Air Pollution and Noise Control"),
    (136, "Environment : Environmental Monitoring"),
    # (137, "Environment : Fuel Cells"),
    (138, "Environment : Maritime Pollution Control"),
    (139, "Environment : Sanitation and Remediation"),
    (140, "Environment : Waste management and recycling"),
    # (141, "Environment : Waste management and recycling : Hazardous Waste Management"),
    # (142, "Environment : Waste management and recycling : Non-Metal Waste and Scrap Recycling"),
    # (143, "Environment : Waste management and recycling : Sewage Collection and Treatment"),
    # (144, "Environment : Waste to Energy"),
    (145, "Water : Water management"),
    # (146, "Environment and Water"),
    (147, "Financial and Professional Services"),
    (148, "Financial and Professional Services : Asset Management"),
    (149, "Financial and Professional Services : Banking"),
    (150, "Financial and Professional Services : Banking : Commercial Banking"),
    (151, "Financial and Professional Services : Banking : Investment Banking"),
    (152, "Financial and Professional Services : Banking : Private Banking"),
    (153, "Financial and Professional Services : Banking : Retail Banking"),
    (154, "Financial and Professional Services : Capital Markets"),
    (155, "Financial and Professional Services : Capital Markets : Hedge Funds"),
    (156, "Financial and Professional Services : Capital Markets : Private Equity"),
    (157, "Financial and Professional Services : Capital Markets : Venture Capital"),
    (158, "Financial and Professional Services : Foreign Exchange"),
    (159, "Financial and Professional Services : Insurance"),
    (160, "Financial and Professional Services : Insurance : Commercial Insurance"),
    (161, "Financial and Professional Services : Insurance : Home Insurance"),
    (162, "Financial and Professional Services : Insurance : Life Insurance"),
    (163, "Financial and Professional Services : Insurance : Motor Insurance"),
    (164, "Financial and Professional Services : Insurance : Travel Insurance"),
    (165, "Financial and Professional Services : Listings"),
    # (166, "Financial and Professional Services : Professional Services"),
    (167, "Financial and Professional Services : Accountancy services"),
    (168, "Financial and Professional Services : Legal services"),
    (169, "Financial and Professional Services : Management consultancy"),
    (170, "Food and drink"),
    (171, "Food and drink : Bakery Products"),
    (172, "Food and drink : Alcoholic Drinks"),
    (173, "Food and drink : Brewing"),
    (174, "Food and drink : Dairy Products"),
    (175, "Food and drink : Food and Drink Manufacturing"),
    (176, "Food and drink : Frozen and Chilled Foods"),
    (177, "Food and drink : Fruit and Vegetables"),
    (178, "Food and drink : Meat Products"),
    (179, "Food and drink : Pet Food"),
    (180, "Food and drink : Ready Meals"),
    (181, "Food and drink : Secondary Food Processing"),
    # (182, "Food and Drink : Tobacco Products"),
    (183, "Consumer and retail : Giftware"),
    (184, "Sports economy"),
    (185, "Sports economy : Major sports events"),
    (186, "Healthcare and Medical"),
    # (187, "Healthcare and Medical : Healthcare Marketing and Sales"),
    # (188, "Healthcare and Medical : Healthcare Marketing and Sales : Healthcare Retail"),
    # (189, "Healthcare and Medical : Healthcare Marketing and Sales : Healthcare Wholesale"),
    (190, "Healthcare Services"),
    # (191, "Healthcare Services : Dentists"),
    # (192, "Healthcare Services : Medical Practice"),
    # (193, "Healthcare Services : Nursing Homes"),
    # (194, "Healthcare Services : Private Sector"),
    # (195, "Healthcare Services : Public Sector"),
    # (196, "Healthcare Services : Vets"),
    (197, "Medical devices and equipment : Consumables and equipment"),
    # (198, "Healthcare and Medical : Medical Devices and Systems"),
    # (199, "Healthcare and Medical : Medical Devices and Systems : Optical Precision Instruments"),
    (200, "Medical devices and equipment"),
    # (201, "Medical devices and equipment : Dental Aesthetics"),
    # (202, "Medical devices and equipment : Glass"),
    # (203, "Medical devices and equipment : Spectacles and Unmounted Lenses"),
    (204, "Healthcare and Medical : Lab Services"),
    (205, "Consumer and retail : Household Goods"),
    # (206, "ICT"),
    (207, "Consumer and retail : Leisure and tourism"),
    # (208, "Consumer and retail : Leisure and Tourism : Gaming"),
    # (209, "Consumer and retail : Leisure and Tourism : Gaming : Casino Gambling"),
    # (210, "Consumer and retail : Leisure and Tourism : Gaming : Mass-Market Gambling"),
    (211, "Sports economy : Sports infrastructure"),
    # (212, "Life Sciences"),
    (213, "Maritime"),
    # (214, "Mass Transport"),
    (215, "Advanced Engineering : Mechanical Electrical and Process Engineering"),
    (216, "Advanced Engineering : Metallurgical Process Plant"),
    (217, "Advanced Engineering : Metals, minerals and materials"),
    (218, "Advanced Engineering : Metals, minerals and materials : Ceramics"),
    (219, "Advanced Engineering : Metals, minerals and materials : Composite Materials"),
    (220, "Advanced Engineering : Metals, minerals and materials : Elastomers and Rubbers"),
    (221, "Advanced Engineering : Metals, minerals and materials : Metals"),
    (222, "Advanced Engineering : Metals, minerals and materials : Minerals"),
    (223, "Advanced Engineering : Metals, minerals and materials : Plastics"),
    (224, "Mining"),
    # (225, "More Sectors"),  # not cdms/spreadsheet
    (226, "Energy : Oil and Gas"),
    (227, "Maritime : Ports and terminals"),
    # (228, "Power"),
    (229, "Energy : Civil nuclear"),
    (230, "Energy : Civil nuclear : Nuclear decommissioning"),
    (231, "Railways"),
    (232, "Energy : Renewable energy"),
    (233, "Energy : Renewable energy : Biomass"),
    (234, "Energy : Renewable energy : Geothermal"),
    (235, "Energy : Renewable energy : Hydro"),
    (236, "Energy : Renewable energy : Solar"),
    (237, "Energy : Renewable energy : Marine and tidal"),
    (238, "Energy : Renewable energy : Wave"),
    # (239, "Energy : Renewable Energy : Wind"),
    (240, "Energy : Renewable energy : Offshore wind"),
    (241, "Energy : Renewable energy : Onshore wind"),
    (242, "Consumer and retail"),

    (243, "Security"),
    (244, "Security : Cyber security"),
    (245, "Technology and smart cities : Software"),
    # (246, "Technology and smart cities : Software : Biometrics"),
    # (247, "Technology and smart cities : Software : E-Procurement"),
    # (248, "Technology and smart cities : Software : Financial Applications"),
    # (249, "Technology and smart cities : Software : Healthcare Applications"),
    # (250, "Technology and smart cities : Software : Industry Applications"),
    # (251, "Technology and smart cities : Software : Online Retailing"),
    # (252, "Technology and smart cities : Software : Security Related Software"),
    # (253, "Technology and smart cities : Software : Support Services"),
    # (254, "Technology and smart cities : Software : Support Services : Equipment Maintenance
    # and Repair"),
    #(255, "Technology and smart cities : Software : Support Services : Internet Service
    # Providers"),
    (256, "Consumer and retail : Textiles, Interior Textiles and Carpets"),
    (257, "Water"),

    (258, "Technology and smart cities"),
    (259, "Financial and Professional Services : Technology"),
    (260, "Consumer and retail : Jewellery"),
    (261, "Consumer and retail : Tableware"),
    (262, "Consumer and retail : Furniture and Furnishings"),
    (263, "Agriculture, horticulture, fisheries and pets : Engineering and precision farming"),
    (264, "Pharmaceuticals and biotechnology : Research and development"),
    (265, "Agriculture, horticulture, fisheries and pets : Livestock, pets and horses"),

    (266, "Consumer and retail : Clothing, footwear and fashion : Accessories, bags and luggage"),
    (267, "Consumer and retail : Clothing, footwear and fashion : Children's apparel"),
    (268, "Consumer and retail : Clothing, footwear and fashion : Children's footwear"),
    (269, "Consumer and retail : Clothing, footwear and fashion : Men's apparel"),
    (270, "Consumer and retail : Clothing, footwear and fashion : Men's footwear"),
    (271, "Consumer and retail : Clothing, footwear and fashion : Sports and leisurewear"),
    (272, "Consumer and retail : Clothing, footwear and fashion : Women's apparel"),
    (273, "Consumer and retail : Clothing, footwear and fashion : Women's footwear"),
    (274, "Consumer and retail : Cosmetics and beauty"),
    (275, "Consumer and retail : Leisure and tourism : Casual dining"),
    (276, "Consumer and retail : Leisure and tourism : Hotels and hospitality"),
    (277, "Consumer and retail : Leisure and tourism : Travel"),
    (278, "Consumer and retail : Luxury"),
    (279, "Consumer and retail : Supermarkets"),
    (280, "Consumer and retail : Electronic consumer products"),
    (281, "Creative industries : Design : Industrial design"),
    (282, "Creative industries : Design : Interior design"),
    (283, "Creative industries : Experience economy : Art"),
    (284, "Creative industries : Experience economy : Attractions"),
    (285, "Creative industries : Experience economy : Museums"),
    (286, "Creative industries : Film and tv : Broadcasting"),
    (287, "Creative industries : Film and tv : Post production"),
    (288, "Creative industries : Film and tv : Production and finance"),
    (289, "Creative industries : Games : Development"),
    (290, "Creative industries : Games : Esports"),
    (291, "Creative industries : Games : Publishing"),
    (292, "Creative industries : Immersive technology"),
    (293, "Creative industries : Media services"),
    (294, "Creative industries : Music : Distribution"),
    (295, "Creative industries : Music : Live performances"),
    (296, "Creative industries : Music : Management"),
    (297, "Creative industries : Music : Publishing"),
    (298, "Creative industries : Music : Recorded music"),
    (299, "Education and training : Curriculum, qualifications, assessment, inspection and "
          "quality assurance"),
    (300, "Education and training : Early years"),
    (301, "Education and training : Educational technology"),
    (302, "Education and training : English language training"),
    (303, "Education and training : Higher education"),
    (304, "Education and training : Higher education : Curriculum, qualifications, assessment "
          "inspection and quality assurance"),
    (305, "Education and training : Higher education : Professional"),
    (306, "Education and training : Higher education : Teacher training"),
    (307, "Education and training : Higher education : Universities"),
    (308, "Education and training : Schools"),
    (309, "Education and training : Special educational needs and disabilities"),
    (310, "Education and training : Special educational needs and disabilities : Consultancy"),
    (311, "Education and training : Special educational needs and disabilities : Curriculum, "
          "qualifications, assessment, inspection and quality assurance"),
    (312, "Education and training : Special educational needs and disabilities : Early years and "
          "schools"),
    (313, "Education and training : Special educational needs and disabilities : Educational "
          "technology equipment and supplies"),
    (314, "Education and training : Special educational needs and disabilities : Higher education "
          "and technical and vocational education and training"),
    (315, "Education and training : Special educational needs and disabilities : Teacher training"),
    (316, "Education and training : Support services"),
    (317, "Education and training : Support services : Construction"),
    (318, "Education and training : Support services : Consultancy and professional services"),
    (319, "Education and training : Support services : Equipment and supplies"),
    (320, "Education and training : Support services : Facilities management"),
    (321, "Education and training : Technical and vocational education and training"),
    (322, "Education and training : Technical and vocational education and training : Colleges "
          "and further education"),
    (323, "Education and training : Technical and vocational education and training : Consultancy"),
    (324, "Education and training : Technical and vocational education and training : Curriculum, "
          "qualifications, assessment, inspection and quality assurance"),
    (325, "Education and training : Technical and vocational education and training : Oil "
          "and gas and mining"),
    (326, "Education and training : Technical and vocational education and training : Training"),
    (327, "Food and drink : Non-alcoholic drinks"),
    (328, "Food and drink : Free from"),
    (329, "Food and drink : Organic"),
    (330, "Sports economy : Sports development and policy"),
    (331, "Sports economy : Sports infrastructure : Sports Architecture"),
    (332, "Sports economy : Sports infrastructure : Sports Construction"),
    (333, "Sports economy : Sports infrastructure : Stadia fit out"),
    (334, "Financial and Professional Services : Accountancy services : Commercial accounting"),
    (335, "Financial and Professional Services : Accountancy services : Retail accounting"),
    (336, "Financial and Professional Services : Legal services : Commercial legal services"),
    (337, "Financial and Professional Services : Legal services : Retail legal services"),
    (338, "Agriculture, horticulture, fisheries and pets : Advisory services"),
    (339, "Agriculture, horticulture, fisheries and pets : Arable crops"),
    (340, "Agriculture, horticulture, fisheries and pets : Arable crops : Fertilisers and "
          "pesticides"),
    (341, "Agriculture, horticulture, fisheries and pets : Arable crops : Harvest and early stage "
         "processing"),
    (342, "Agriculture, horticulture, fisheries and pets : Arable crops : Seeds and plant "
          "varieties"),
    (343, "Agriculture, horticulture, fisheries and pets : Arable crops : Soil management systems"),
    (344, "Agriculture, horticulture, fisheries and pets : Engineering and precision farming"),
    (345, "Agriculture, horticulture, fisheries and pets : Engineering and precision farming : "
          "Machinery"),
    (346, "Agriculture, horticulture, fisheries and pets : Engineering and precision farming : "
          "Technology"),
    (347, "Agriculture, horticulture, fisheries and pets : Fisheries and aquaculture"),
    (348, "Agriculture, horticulture, fisheries and pets : Fisheries and aquaculture : "
          "Broodstock and genetics"),
    (349, "Agriculture, horticulture, fisheries and pets : Fisheries and aquaculture : Cages and "
          "farming systems"),
    (350, "Agriculture, horticulture, fisheries and pets : Fisheries and aquaculture : Nutrition "
          "and husbandry"),
    (351, "Agriculture, horticulture, fisheries and pets : Forestry and logging"),
    (352, "Agriculture, horticulture, fisheries and pets : Horticulture"),
    (353, "Agriculture, horticulture, fisheries and pets : Horticulture : Fruit and vegetable "
          "production"),
    (354, "Agriculture, horticulture, fisheries and pets : Horticulture : Ornamental plants and "
          "flowers"),
    (355, "Agriculture, horticulture, fisheries and pets : Infrastructure"),
    (356, "Agriculture, horticulture, fisheries and pets : Infrastructure : Buildings"),
    (357, "Agriculture, horticulture, fisheries and pets : Infrastructure : On-farm and cold "
          "chain storage and transport"),
    (358, "Agriculture, horticulture, fisheries and pets : Infrastructure : Water storage, "
          "management and distribution"),
    (359, "Agriculture, horticulture, fisheries and pets : Livestock, pets and horses"),
    (360, "Agriculture, horticulture, fisheries and pets : Livestock, pets and horses : Breeding "
          "stock and genetics"),
    (361, "Agriculture, horticulture, fisheries and pets : Livestock, pets and horses : Health, "
          "welfare and veterinary services"),
    (362, "Agriculture, horticulture, fisheries and pets : Livestock, pets and horses : Livestock feed and nutrition"),
    (363, "Agriculture, horticulture, fisheries and pets : Livestock, pets and horses : Tagging "
          "and traceability"),
    (364, "Healthcare services : Digital and data"),
    (365, "Healthcare services : Education and training"),
    (366, "Healthcare services : Health systems management"),
    (367, "Healthcare services : Infrastructure"),
    (368, "Healthcare services : Social care"),
    (369, "Medical devices and equipment : Digital and data"),
    (370, "Medical devices and equipment : Implantable devices"),
    (371, "Medical devices and equipment : In vitro diagnostic devices"),
    (372, "Pharmaceuticals and biotechnology : Digital and data"),
    (373, "Pharmaceuticals and biotechnology : Research and development"),
    (374, "Energy : Renewable energy : Electrical networks"),
    (375, "Energy : Renewable energy : Energy storage"),
    (376, "Energy : Renewable energy : Hydrogen"),
    (377, "Energy : Renewable energy : Industrial decarbonisation"),
    (378, "Energy : Renewable energy : Waste to value"),
    (379, "Environment : Clean growth services"),
    (380, "Water : Flood resilience"),
    (381, "Water : Wastewater management"),
    (382, "Aerospace : Component manufacturing : Aerostructures"),
    (383, "Aerospace : Component manufacturing : Systems"),
    (384, "Maritime : Marine engineering"),
    (385, "Maritime : Marine engineering : Autonomous vessels and systems"),
    (386, "Maritime : Marine engineering : Composites and other specialist technical areas"),
    (387, "Maritime : Marine engineering : Construction and manufacture"),
    (388, "Maritime : Marine engineering : Digital shipping"),
    (389, "Maritime : Marine engineering : Engineering and interior design"),
    (390, "Maritime : Marine engineering : Engineering consultancy"),
    (391, "Maritime : Marine engineering : Fit out and refits"),
    (392, "Maritime : Marine engineering : Green marine"),
    (393, "Maritime : Marine engineering : Leisure marine"),
    (394, "Maritime : Marine engineering : Marine science"),
    (395, "Maritime : Marine engineering : Maritime equipment and systems"),
    (396, "Maritime : Marine engineering : Project management"),
    (397, "Maritime : Marine engineering : Research and development"),
    (398, "Maritime : Maritime services"),
    (399, "Maritime : Maritime services : Accounting and financial services"),
    (400, "Maritime : Maritime services : Classification"),
    (401, "Maritime : Maritime services : Consultancy"),
    (402, "Maritime : Maritime services : Human resource management"),
    (403, "Maritime : Maritime services : Marine insurance"),
    (404, "Maritime : Maritime services : Maritime charities"),
    (405, "Maritime : Maritime services : Maritime law and arbitration"),
    (406, "Maritime : Maritime services : Media and pr"),
    (407, "Maritime : Maritime services : Ship finance"),
    (408, "Maritime : Maritime services : Ship management"),
    (409, "Maritime : Maritime services : Shipbroking"),
    (410, "Maritime : Maritime services : Training and education"),
    (411, "Space"),
    (412, "Space : Component manufacturing"),
    (413, "Space : Component manufacturing : Communications"),
    (414, "Space : Component manufacturing : Electronics"),
    (415, "Space : Component manufacturing : Optics"),
    (416, "Space : Component manufacturing : Propulsion"),
    (417, "Space : Component manufacturing : Robotics"),
    (418, "Space : Component manufacturing : Satellite bus"),
    (419, "Space : Services"),
    (420, "Space : Services : Artificial intelligence and data"),
    (421, "Space : Services : Communications"),
    (422, "Space : Services : Earth observation"),
    (423, "Space : Services : Ground based"),
    (424, "Space : Services : Launch"),
    (425, "Space : Services : Satellite operation"),
    (426, "Technology and smart cities"),

    (427, "Technology and smart cities : Communications : Internet service providers"),
    (428, "Technology and smart cities : Communications : Wireless internet of things"),
    (429, "Technology and smart cities : Software : Software as a service"),
    (430, "Technology and smart cities : Hardware : 5G"),
    (431, "Technology and smart cities : Hardware : Data centres"),
    (432, "Technology and smart cities : Hardware : Internet of things"),
    (433, "Technology and smart cities : Hardware : Photonics"),
    (434, "Technology and smart cities : Hardware : Semiconductors"),
    (435, "Technology and smart cities : Hardware : Sensors"),
    (436, "Technology and smart cities : Hardware : Telecommunications and Electronics systems"),
    (437, "Technology and smart cities : Software : 5G"),
    (438, "Technology and smart cities : Software : Artificial intelligence"),
    (439, "Technology and smart cities : Software : Blockchain"),
    (440, "Technology and smart cities : Software : Cloud Services"),
    (441, "Technology and smart cities : Software : Data Analytics"),
    (442, "Technology and smart cities : Software : Internet of things"),
    (443, "Technology and smart cities : Software : Sensors"),


)

SECTORS = sorted(_SECTORS, key=lambda data: data[1])

TEAMS = (
    ("team", "Trade (TD or ST)"),
    ("investment", "Investment (ITFG or IG)"),
    ("dso", "DSO"),
    ("other", "Other HQ Team"),
    ("itt", "International Trade Team"),
    ("obn", "Overseas Business Network"),
    ("post", "Overseas Post"),
    ("tcp", "Trade Challenge Partners (TCP)"),
)

HQ_TEAM_REGION_OR_POST = tuple([

    ("team:1", "TD - Events - Financial & Professional Business Services"),
    ("team:2", "TD - Events - Education"),
    ("team:3", "TD - Events - Services"),
    ("team:4", "TD - Events - Creative Industries"),
    ("team:5", "TD - Events - Retail"),
    ("team:6", "TD - Events - Large Events Support"),
    ("team:7", "TD - Events - Rapid Response"),
    ("team:8", "TD - Events - Large Events"),
    ("team:9", "TD - Events - Venture Capital"),
    ("team:10", "TD - Events - Energy"),
    ("team:11", "TD - Events - Advanced Manufacturing"),
    ("team:12", "TD - Events - Advanced Engineering"),
    ("team:13", "TD - Events - Agrifood"),
    ("team:14", "TD - Events - Consumer Goods"),
    ("team:15", "TD - Events - Maritime"),
    ("team:16", "TD - Events - Advanced Manufacturing - Support"),
    ("team:17", "TD - Events - Planning and Procurement"),
    ("team:18", "TD - Finance & Performance"),
    ("team:19", "TD - Technology, Innovation and Events - Venture Capital Unit"),
    ("team:20", "TD - Technology, Innovation and Events - Science and Innovation"),
    ("team:21", "TD - Technology, Innovation and Events - Technology Partnerships"),
    ("team:22", "TD - Technology, Innovation and Events - Open to Export"),
    ("team:23", "TD - Technology, Innovation and Events"),
    ("team:24", "TD - Events Delivery & Performance"),
    ("team:25", "TD - Events - BDV"),
    ("team:26", "TD - Events - Markets"),
    ("team:27", "TD - TAP Team"),
    ("team:28", "TD - Business Development"),
    ("team:29", "TD - Events - Sport"),
    ("team:30", "TD - Events - Infrastructure & Life Sciences"),
    ("team:31", "TD - Events - Infrastructure"),
    ("team:32", "TD - Infrastructure & Life Sciences"),
    ("team:33", "TD - Events - ICT"),
    ("team:34", "TD - Events - Transport"),
    ("team:35", "TD - Events - Healthcare"),
    ("team:36", "TD - Events - Construction"),
    ("team:37", "TD - Events - Open to Export"),
    ("team:38", "ST - Managing Director and PA"),
    ("team:39", "ST - Infrastructure and Life Science - Healthcare Pharma and Bio"),
    ("team:40", "ST - Infrastructure & Life Science - Construction/Mass Transport"),
    ("team:41", "ST - Infrastructure and Life Science - Low Carbon Env Water"),
    ("team:42", "ST - Infrastructure and Life Science - High Value Opportunities"),
    ("team:43", "ST - Infrastructure and Life Science - Support Team"),
    ("team:44", "ST - Infrastructure and Life Science - Sport"),
    ("team:45", "ST - High Value Opportunities Activities"),
    ("team:46", "ST - Service Industries - Education and Experience Economy"),
    ("team:47", "ST - Service Industries - Financial Professional and Business"),
    ("team:48", "ST - Service Industries - Retail and Lifestyle"),
    ("team:49", "ST - Service Industries - Agri-Food Drink & Aid Funded Business"),
    ("team:50", "ST - Director - Service Industries"),
    ("team:51", "ST - Service Industries - Support Team"),
    ("team:52", "ST - Service Industries - Creative Industries"),
    ("team:53", "ST - Advanced Manufacturing - Support Team"),
    ("team:54", "ST - Advanced Manufacturing - Advanced Engineering"),
    ("team:55", "ST - Advanced Manufacturing - ICT"),
    ("team:56", "ST - Advanced Manufacturing - Energy"),
    ("team:57", "ST - Middle East"),
    ("team:58", "ST - Central and Latin America"),
    ("team:59", "ST - Russia - Turkey - Central Asia"),
    ("team:60", "ST - Africa"),
    ("team:61", "ST - Dir - Emerging Markets - China - Southern Asia"),
    ("team:62", "ST - Emerging Markets - China - Southern Asia - Support"),
    ("team:63", "ST - Emerging Markets"),
    ("team:64", "ST - China"),
    ("team:65", "ST - South Asia"),
    ("team:66", "ST - South East Asia"),
    ("team:67", "ST - Dir - Developed Markets"),
    ("team:68", "ST - Developed Markets - Support Team"),
    ("team:69", "ST - North America - East Asia - Australasia - Caribbean"),
    ("team:70", "ST - Europe"),
    ("team:71", "ST - Group Resources - Support Team"),
    ("team:72", "ST - E-Exporting Programme"),

    ("investment:1", "ITFG - E-Business Projects Team"),
    ("investment:2", "ITFG - Overseas Resources Team"),
    ("investment:3", "ITFG - ICT & Data Policy and Support"),
    ("investment:4", "ITFG - E-Business Operational Support Team"),
    ("investment:5", "ITFG - Director ITFG & PA"),
    ("investment:6", "ITFG - Finance Team"),
    ("investment:7", "ITFG - Business Planning Team"),
    ("investment:8", "IG - Regeneration Investment Organisation (RIO)"),
    ("investment:9", "IG - Global Accounts - Director & Deputy Director & PA"),
    ("investment:10", "IG - Global Accounts - IT Software & Creative"),
    ("investment:11", "IG - Global Accounts - Electronics & Communications"),
    ("investment:12", "IG - Global Accounts - Financial & Business Services"),
    ("investment:13", "IG - Global Accounts - Energy & Infrastructure"),
    ("investment:14", "IG - Global Accounts - Adv Man - Auto, Rail MEPE"),
    ("investment:15", "IG - Global Accounts - Adv Man - Aero, Space, Chem"),
    ("investment:16", "IG - Global Accounts - Life Science, Agri- Tech"),
    ("investment:17", "IG - Global Operations - Global Entrepreneurs Programme"),
    ("investment:18", "IG - Global Operations - Graduate Entrepreneurs"),
    ("investment:19", "IG - Global Operations - Network Linkages & Professional Development"),
    ("investment:20", "IG - Global Operations - In Market Strategies & Development"),
    ("investment:21", "IG - Strategy/Policy/Local Engagement - Director & PA"),
    ("investment:22", "IG - Strategy/Policy/Local Engagement - Strategy"),
    ("investment:23", "IG - Strategy/Policy/Local Engagement - Global Intelligence"),
    ("investment:24", "IG - Strategy/Policy/Local Engagement - Local Engagement & Delivery"),
    ("investment:25", "IG - Strategy/Policy/Local Engagement - National & Local Policy"),
    ("investment:26", "IG - Specialists - Advanced Manufacturing"),
    ("investment:27", "IG - Specialists - Knowledge Intensive Industry"),
    ("investment:28", "IG - Specialists - Energy & Infrastructure"),
    ("investment:29", "IG - Specialists - Life Sciences"),
    ("investment:30", "IG - Finance & Business Planning"),
    ("investment:31", "IG - Global Intelligence Unit"),
    ("investment:32", "IG - SR - Strategic Accounts"),
    ("investment:33", "IG - SR - Institutional Investment"),
    ("investment:34", "IG - Global Operations - FDI Projects - Advanced Engineering"),
    ("investment:35", "IG - Global Operations - Director & PA"),
    ("investment:36", "IG - Global Operations - FDI Projects - Energy and Infrastructure"),
    ("investment:37", "IG - Global Operations - Briefing Tours and Visits"),
    ("investment:38", "IG - Global Operations and Network Performance"),
    ("investment:39", "IG - Global Operations - Deputy Director"),
    ("investment:40", "IG - Global Operations - Shared Services"),
    ("investment:41", "IG - UKAN Involvement"),
    ("investment:42", "IG - Strategy & Policy - Resources and Finance"),
    ("investment:43", "IG - Strategy & Policy - FDI Projects - Financial Services"),
    ("investment:44", "IG - Strategy & Policy - FDI Contract - Networks & Partnerships"),
    ("investment:45", "Business Environment Advisory Team"),
    ("investment:46", "IG - Strategy & Policy - Briefing Tours and Visits"),
    ("investment:47", "IG - Strategy & Policy - Director & PA"),
    ("investment:48", "IG - Strategy & Policy - FDI Projects - Electronics and Comms"),
    ("investment:49", "IG - Strategy & Policy - Deputy Director"),
    ("investment:50", "IG - Strategy & Policy - Information Hub"),
    ("investment:51", "IG - Strategy & Policy - Local Policy & Engagement - DAs & Eng"),
    ("investment:52", "IG - CPI - FDI Projects - Life Sciences - Food & Drink"),
    ("investment:53", "IG - CPI - FDI Projects - New Technologies"),
    ("investment:54", "IG - Campaigns and Special Programmes"),
    ("investment:55", "IG - Tech City Investment Organisation"),
    ("investment:56", "GREAT Investors"),

    ("dso:1", "DSO Head Office"),
    ("dso:2", "DSO Cyber Security Export Team"),
    ("dso:3", "DSO Business Development - Market Analysis"),
    ("dso:4", "DSO Director - Business Development - Events"),
    ("dso:5", "DSO - Business Development - Events"),
    ("dso:6", "DSO - Director - Business Development - Support to Business"),
    ("dso:7", "DSO - Head - Business Development - SME Team"),
    ("dso:8", "DSO - Business Development - Exportability"),
    ("dso:9", "DSO - Business Development - SME Team"),
    ("dso:10", "DSO - Business Development - Key Account Management"),
    ("dso:11", "DSO - Business Development - Mid Sized Businesses"),
    ("dso:12", "DSO - Director - RD1"),
    ("dso:13", "DSO - Deputy Director - RD 1"),
    ("dso:14", "DSO - RD 1A"),
    ("dso:15", "DSO - RD 1B"),
    ("dso:16", "DSO - RD 1C"),
    ("dso:17", "DSO - RD 1D"),
    ("dso:18", "DSO - RD 1E"),
    ("dso:19", "DSO - Director - RD2"),
    ("dso:20", "DSO - RD 2A"),
    ("dso:21", "DSO - Deputy Director - RD2"),
    ("dso:22", "DSO - RD 2B"),
    ("dso:23", "DSO - RD 2C"),
    ("dso:24", "DSO - RD 2D"),
    ("dso:25", "DSO - Senior Military Advisors"),
    ("dso:26", "DSO Policy and Resources"),
    ("dso:27", "DSO EM Exhibitions"),
    ("dso:28", "DSO Export Support Team (Bovington)"),
    ("dso:29", "DSO Export Support Team (Larkhill)"),
    ("dso:30", "DSO Director Business Development"),

    ('obn:1', 'Burma - British Chamber of Commerce Myanmar'),
    ('obn:2', 'Cambodia - British Chamber of Commerce'),
    ('obn:3', 'Chile - British Chamber of Commerce Chile'),
    ('obn:4', 'China - CBBC'),
    ('obn:5', 'Colombia - UK Colombia Trade'),
    ('obn:6', 'Czech Republic - British Chamber of Commerce'),
    ('obn:7', 'Ghana - British Chamber of Commerce'),
    ('obn:8', 'Hungary - British Business Centre Budapest'),
    ('obn:9', 'India - UKIBC'),
    ('obn:10', 'Indonesia - British Chamber of Commerce'),
    ('obn:11', 'Kazakhstan - British Chamber of Commerce'),
    ('obn:34', 'Kenya - British Chamber of Commerce Kenya'),
    ('obn:12', 'Kuwait - Kuwait British Business Centre'),
    ('obn:13', 'Malaysia - British Malaysian Chamber of Commerce'),
    ('obn:14', 'Morocco - British Chamber of Commerce'),
    ('obn:15', 'Pakistan - British Business Centre Karachi'),
    ('obn:16', 'Philippines - British Chamber of Commerce'),
    ('obn:17', 'Poland - British Polish Chamber of Commerce'),
    ('obn:18', 'Qatar - British Chamber of Commerce'),
    ('obn:19', 'Romania - British-Romanian Chamber of Commerce'),
    ('obn:20', 'Saudi Arabia - Arabian Enterprise Incubators (AEI Saudi)'),
    ('obn:21', 'Singapore - British Chamber of Commerce'),
    ('obn:22', 'Slovakia - British Slovak Business Centre'),
    ('obn:23', 'Slovenia - British Slovenian Chamber of Commerce'),
    ('obn:24', 'South Africa - British Chamber of Business in Southern Africa'),
    ('obn:25', 'South East Asia - UK-ASEAN Business Council'),
    ('obn:26', 'South Korea - British Chamber of Commerce Korea'),
    ('obn:27', 'Taiwan - British Chamber of Commerce Taipei'),
    ('obn:28', 'Thailand - British Chamber of Commerce'),
    ('obn:29', 'Turkey - British Chamber of Commerce'),
    ('obn:30', 'UAE - British Centres for Business'),
    ('obn:32', 'USA - Altios'),
    ('obn:33', 'USA - OCO Global'),
    ('obn:31', 'Vietnam - British Business Group'),

    ("other:1", "DIT Education"),
    ("other:2", "Healthcare UK"),
    ("other:3", "Offshore Wind Investment Organisation"),
    ("other:4", "Tech City Project"),
    ("other:5", "BG - Tech City"),
    ("other:6", "Financial Services Organisation (FSO)"),
    ("other:7", "Export Control Unit"),
    ("other:8", "Life Sciences Organisation"),
    ("other:9", "UK Export Finance"),
    ("other:10", "GREAT BRITAIN Campaign"),

    ('itt:DIT Dubai Regional Hub', 'DIT Dubai Regional Hub'),
    ('itt:DIT North East Regional International Trade Office',
     'DIT North East Regional International Trade Office'),
    ('itt:DIT South West', 'DIT South West'),
    ('itt:DIT Team East', 'DIT Team East'),
    ('itt:DIT Team East Midlands - International Trade Team',
     'DIT Team East Midlands - International Trade Team'),
    ('itt:DIT Team South East - International Trade Team',
     'DIT Team South East - International Trade Team'),
    ('itt:DIT Team West Midlands - Birmingham',
     'DIT Team West Midlands - Birmingham'),
    ('itt:DIT Team West Midlands - Black Country',
     'DIT Team West Midlands - Black Country'),
    ('itt:DIT Team West Midlands - Coventry', 'DIT Team West Midlands - Coventry'),
    ('itt:DIT Team West Midlands - Hereford and Worcester',
     'DIT Team West Midlands - Hereford and Worcester'),
    ('itt:DIT Team West Midlands - NEC', 'DIT Team West Midlands - NEC'),
    ('itt:DIT Team West Midlands - Regional and LLP',
     'DIT Team West Midlands - Regional and LLP'),
    ('itt:DIT Team West Midlands - Shropshire',
     'DIT Team West Midlands - Shropshire'),
    ('itt:DIT Team West Midlands - Staffordshire',
     'DIT Team West Midlands - Staffordshire'),
    ('itt:DIT West Midlands Team - Regional Team',
     'DIT West Midlands Team - Regional Team'),
    ('itt:DIT Yorkshire', 'DIT Yorkshire'),
    (
        'itt:DIT Yorkshire and Humber Regional Sector Specialists',
        'DIT Yorkshire and Humber Regional Sector Specialists'
    ),
    ('itt:Invest Northern Ireland (Trade)', 'Invest Northern Ireland (Trade)'),
    ('itt:London International Trade Team', 'London International Trade Team'),
    ('itt:National Chemicals Sector Unit', 'National Chemicals Sector Unit'),
    (
        'itt:Scottish Development International - International Trade Enquiries Team',
        'Scottish Development International - International Trade Enquiries Team'
    ),
    ('itt:The North West International Trade Team',
     'The North West International Trade Team'),
    ('itt:Welsh Government', 'Welsh Government'),

    ("post:Afghanistan - Kabul", "Afghanistan - Kabul"),
    ("post:Albania - Tirana", "Albania - Tirana"),
    ("post:Algeria - Algiers", "Algeria - Algiers"),
    ("post:Angola - Luanda", "Angola - Luanda"),
    ("post:Antigua - St John's", "Antigua - St John's"),
    ("post:Argentina - Buenos Aires", "Argentina - Buenos Aires"),
    ("post:Armenia - Yerevan", "Armenia - Yerevan"),
    ("post:Australia - Brisbane", "Australia - Brisbane"),
    ("post:Australia - Canberra", "Australia - Canberra"),
    ("post:Australia - Melbourne", "Australia - Melbourne"),
    ("post:Australia - Perth", "Australia - Perth"),
    ("post:Australia - Sydney", "Australia - Sydney"),
    ("post:Austria - Vienna", "Austria - Vienna"),
    ("post:Azerbaijan - Baku", "Azerbaijan - Baku"),
    ("post:Bahamas - Nassau", "Bahamas - Nassau"),
    ("post:Bahrain - Manama", "Bahrain - Manama"),
    ("post:Bangladesh - Dhaka", "Bangladesh - Dhaka"),
    ("post:Barbados - Bridgetown", "Barbados - Bridgetown"),
    ("post:Belarus - Minsk", "Belarus - Minsk"),
    ("post:Belgium - Brussels", "Belgium - Brussels"),
    ("post:Belize - Belmopan", "Belize - Belmopan"),
    ("post:Bolivia - La Paz", "Bolivia - La Paz"),
    ("post:Bosnia and Herzegovina - Sarajevo", "Bosnia and Herzegovina - Sarajevo"),
    ("post:Botswana - Gaborone", "Botswana - Gaborone"),
    ("post:Brazil - Belo Horizonte", "Brazil - Belo Horizonte"),
    ("post:Brazil - Brasilia", "Brazil - Brasilia"),
    ("post:Brazil - Porto Alegre", "Brazil - Porto Alegre"),
    ("post:Brazil - Recife", "Brazil - Recife"),
    ("post:Brazil - Rio de Janeiro", "Brazil - Rio de Janeiro"),
    ("post:Brazil - Sao Paulo", "Brazil - Sao Paulo"),
    ("post:Brunei - Bandar Seri Begawan", "Brunei - Bandar Seri Begawan"),
    ("post:Bulgaria - Sofia", "Bulgaria - Sofia"),
    ("post:Burma - Rangoon", "Burma - Rangoon"),
    ("post:Cambodia - Phnom Penh", "Cambodia - Phnom Penh"),
    ("post:Cameroon - Douala", "Cameroon - Douala"),
    ("post:Cameroon - Yaounde", "Cameroon - Yaounde"),
    ("post:Canada - Calgary", "Canada - Calgary"),
    ("post:Canada - Montreal", "Canada - Montreal"),
    ("post:Canada - Ottawa", "Canada - Ottawa"),
    ("post:Canada - Toronto", "Canada - Toronto"),
    ("post:Canada - Vancouver", "Canada - Vancouver"),
    ("post:Chile - Santiago", "Chile - Santiago"),
    ("post:China - Beijing", "China - Beijing"),
    ("post:China - Chongqing", "China - Chongqing"),
    ("post:China - Guangzhou", "China - Guangzhou"),
    ("post:China - Shanghai", "China - Shanghai"),
    ("post:China - Wuhan", "China - Wuhan"),
    ("post:Colombia - Bogota", "Colombia - Bogota"),
    ("post:Congo - Kinshasa", "Congo - Kinshasa"),
    ("post:Costa Rica - San Jose", "Costa Rica - San Jose"),
    ("post:Croatia - Split", "Croatia - Split"),
    ("post:Croatia - Zagreb", "Croatia - Zagreb"),
    ("post:Cuba - Havana", "Cuba - Havana"),
    ("post:Cyprus - Nicosia", "Cyprus - Nicosia"),
    ("post:Czech Republic - Prague", "Czech Republic - Prague"),
    ("post:Denmark - Copenhagen", "Denmark - Copenhagen"),
    ("post:Dominica - Roseau", "Dominica - Roseau"),
    ("post:Dominican Republic - Santo Domingo",
     "Dominican Republic - Santo Domingo"),
    ("post:East Timor - Dili", "East Timor - Dili"),
    ("post:Ecuador - Guayaquil", "Ecuador - Guayaquil"),
    ("post:Ecuador - Quito", "Ecuador - Quito"),
    ("post:Egypt - Alexandria", "Egypt - Alexandria"),
    ("post:Egypt - Cairo", "Egypt - Cairo"),
    ("post:El Salvador - San Salvador", "El Salvador - San Salvador"),
    ("post:Eritria - Asmara", "Eritria - Asmara"),
    ("post:Estonia - Tallinn", "Estonia - Tallinn"),
    ("post:Ethiopia - Addis Ababa", "Ethiopia - Addis Ababa"),
    ("post:Fiji - Suva", "Fiji - Suva"),
    ("post:Finland - Helsinki", "Finland - Helsinki"),
    ("post:France - Bordeaux", "France - Bordeaux"),
    ("post:France - Lille", "France - Lille"),
    ("post:France - Lyon", "France - Lyon"),
    ("post:France - Paris", "France - Paris"),
    ("post:Gabon - Libreville", "Gabon - Libreville"),
    ("post:Gambia - Banjul", "Gambia - Banjul"),
    ("post:Georgia - Tbilisi", "Georgia - Tbilisi"),
    ("post:Germany - Berlin", "Germany - Berlin"),
    ("post:Germany - Dusseldorf", "Germany - Dusseldorf"),
    ("post:Germany - Munich", "Germany - Munich"),
    ("post:Ghana - Accra", "Ghana - Accra"),
    ("post:Greece - Athens", "Greece - Athens"),
    ("post:Greece - Thessaloniki", "Greece - Thessaloniki"),
    ("post:Grenada - St George's", "Grenada - St George's"),
    ("post:Guatemala - Guatemala City", "Guatemala - Guatemala City"),
    ("post:Guyana - Georgetown", "Guyana - Georgetown"),
    ("post:Honduras - Tegucigalpa", "Honduras - Tegucigalpa"),
    ("post:Hong Kong", "Hong Kong"),
    ("post:Hungary - Budapest", "Hungary - Budapest"),
    ("post:Iceland - Reykjavik", "Iceland - Reykjavik"),
    ("post:India - Ahmedabad", "India - Ahmedabad"),
    ("post:India - Bangalore", "India - Bangalore"),
    ("post:India - Chandigarh", "India - Chandigarh"),
    ("post:India - Chennai", "India - Chennai"),
    ("post:India - Hyderabad", "India - Hyderabad"),
    ("post:India - Kolkata", "India - Kolkata"),
    ("post:India - Mumbai", "India - Mumbai"),
    ("post:India - New Delhi", "India - New Delhi"),
    ("post:India - Pune", "India - Pune"),
    ("post:Indonesia - Jakarta", "Indonesia - Jakarta"),
    ("post:Iran - Tehran", "Iran - Tehran"),
    ("post:Iraq - Baghdad", "Iraq - Baghdad"),
    ("post:Iraq - Erbil", "Iraq - Erbil"),
    ("post:Ireland - Dublin", "Ireland - Dublin"),
    ("post:Israel - Tel Aviv", "Israel - Tel Aviv"),
    ("post:Italy - Milan", "Italy - Milan"),
    ("post:Italy - Naples", "Italy - Naples"),
    ("post:Italy - Rome", "Italy - Rome"),
    ("post:Ivory Coast - Abidjan", "Ivory Coast - Abidjan"),
    ("post:Jamaica - Kingston", "Jamaica - Kingston"),
    ("post:Japan - Osaka", "Japan - Osaka"),
    ("post:Japan - Tokyo", "Japan - Tokyo"),
    ("post:Jerusalem", "Jerusalem"),
    ("post:Jordan - Amman", "Jordan - Amman"),
    ("post:Kazakhstan - Almaty", "Kazakhstan - Almaty"),
    ("post:Kazakhstan - Astana", "Kazakhstan - Astana"),
    ("post:Kazakhstan - Atyrau", "Kazakhstan - Atyrau"),
    ("post:Kenya - Nairobi", "Kenya - Nairobi"),
    ("post:Kiribati - Tarawa", "Kiribati - Tarawa"),
    ("post:North Korea - Pyongyang", "North Korea - Pyongyang"),
    ("post:Kosovo - Pristina", "Kosovo - Pristina"),
    ("post:Kuwait", "Kuwait"),
    ("post:Kyrgyzstan - Bishkek", "Kyrgyzstan - Bishkek"),
    ("post:Laos - Vientiane", "Laos - Vientiane"),
    ("post:Latvia - Riga", "Latvia - Riga"),
    ("post:Lebanon - Beirut", "Lebanon - Beirut"),
    ("post:Lesotho - Maseru", "Lesotho - Maseru"),
    ("post:Libya - Tripoli", "Libya - Tripoli"),
    ("post:Lithuania - Vilnius", "Lithuania - Vilnius"),
    ("post:Luxembourg", "Luxembourg"),
    ("post:Macedonia - Skopje", "Macedonia - Skopje"),
    ("post:Madagascar - Antananarivo", "Madagascar - Antananarivo"),
    ("post:Malawi - Lilongwe", "Malawi - Lilongwe"),
    ("post:Malaysia - Kuala Lumpur", "Malaysia - Kuala Lumpur"),
    ("post:Malta - Valletta", "Malta - Valletta"),
    ("post:Mauritius - Port Louis", "Mauritius - Port Louis"),
    ("post:Mexico - Guadalajara", "Mexico - Guadalajara"),
    ("post:Mexico - Mexico City", "Mexico - Mexico City"),
    ("post:Mexico - Monterrey", "Mexico - Monterrey"),
    ("post:Mexico - Tijuana", "Mexico - Tijuana"),
    ("post:Moldova - Chisinau", "Moldova - Chisinau"),
    ("post:Mongolia - Ulaanbaatar", "Mongolia - Ulaanbaatar"),
    ("post:Morocco - Casablanca", "Morocco - Casablanca"),
    ("post:Morocco - Rabat", "Morocco - Rabat"),
    ("post:Mozambique - Maputo", "Mozambique - Maputo"),
    ("post:Namibia - Windhoek", "Namibia - Windhoek"),
    ("post:Nepal - Kathmandu", "Nepal - Kathmandu"),
    ("post:Netherlands - The Hague", "Netherlands - The Hague"),
    ("post:New Zealand - Auckland", "New Zealand - Auckland"),
    ("post:New Zealand - Wellington", "New Zealand - Wellington"),
    ("post:Nigeria - Abuja", "Nigeria - Abuja"),
    ("post:Nigeria - Kaduna", "Nigeria - Kaduna"),
    ("post:Nigeria - Lagos", "Nigeria - Lagos"),
    ("post:Nigeria - Port Harcourt", "Nigeria - Port Harcourt"),
    ("post:Norway - Oslo", "Norway - Oslo"),
    ("post:Oman - Muscat", "Oman - Muscat"),
    ("post:Pakistan -  Islamabad", "Pakistan -  Islamabad"),
    ("post:Pakistan - Karachi", "Pakistan - Karachi"),
    ("post:Pakistan - Lahore", "Pakistan - Lahore"),
    ("post:Panama - Panama City", "Panama - Panama City"),
    ("post:Papua New Guinea - Port Moresby", "Papua New Guinea - Port Moresby"),
    ("post:Paraguay - Asuncion", "Paraguay - Asuncion"),
    ("post:Peru - Lima", "Peru - Lima"),
    ("post:Philippines - Manila", "Philippines - Manila"),
    ("post:Poland - Warsaw", "Poland - Warsaw"),
    ("post:Portugal - Lisbon", "Portugal - Lisbon"),
    ("post:Portugal - Oporto", "Portugal - Oporto"),
    ("post:Portugal - Portimao", "Portugal - Portimao"),
    ("post:Puerto Rico", "Puerto Rico"),
    ("post:Qatar - Doha", "Qatar - Doha"),
    ("post:Republic of Guinea - Conakry", "Republic of Guinea - Conakry"),
    ("post:Romania - Bucharest", "Romania - Bucharest"),
    ("post:Russia - Ekaterinburg", "Russia - Ekaterinburg"),
    ("post:Russia - Moscow", "Russia - Moscow"),
    ("post:Russia - St Petersburg", "Russia - St Petersburg"),
    ("post:Rwanda - Kigali", "Rwanda - Kigali"),
    ("post:San Marino", "San Marino"),
    ("post:Saudi Arabia - Al Khobar", "Saudi Arabia - Al Khobar"),
    ("post:Saudi Arabia - Jeddah", "Saudi Arabia - Jeddah"),
    ("post:Saudi Arabia - Riyadh", "Saudi Arabia - Riyadh"),
    ("post:Senegal - Dakar", "Senegal - Dakar"),
    ("post:Serbia - Belgrade", "Serbia - Belgrade"),
    ("post:Seychelle - Victoria", "Seychelle - Victoria"),
    ("post:Sierra Leone - Freetown", "Sierra Leone - Freetown"),
    ("post:Singapore", "Singapore"),
    ("post:Slovakia - Bratislava", "Slovakia - Bratislava"),
    ("post:Slovenia - Ljubljana", "Slovenia - Ljubljana"),
    ("post:Solomon Islands - Honiara", "Solomon Islands - Honiara"),
    ("post:South Africa - Cape Town", "South Africa - Cape Town"),
    ("post:South Africa - Durban", "South Africa - Durban"),
    ("post:South Africa - Johannesburg", "South Africa - Johannesburg"),
    ("post:South Africa - Pretoria", "South Africa - Pretoria"),
    ("post:South Korea - Seoul", "South Korea - Seoul"),
    ("post:Spain - Barcelona", "Spain - Barcelona"),
    ("post:Spain - Bilbao", "Spain - Bilbao"),
    ("post:Spain - Madrid", "Spain - Madrid"),
    ("post:Sri Lanka - Colombo", "Sri Lanka - Colombo"),
    ("post:St Lucia - Castries", "St Lucia - Castries"),
    ("post:St Vincent - Kingstown", "St Vincent - Kingstown"),
    ("post:Sudan - Khartoum", "Sudan - Khartoum"),
    ("post:Swaziland - Mbabane", "Swaziland - Mbabane"),
    ("post:Sweden - Stockholm", "Sweden - Stockholm"),
    ("post:Switzerland - Berne", "Switzerland - Berne"),
    ("post:Switzerland - Geneva", "Switzerland - Geneva"),
    ("post:Syria - Damascus", "Syria - Damascus"),
    ("post:Taiwan - Taipei", "Taiwan - Taipei"),
    ("post:Tajikistan - Dushanbe", "Tajikistan - Dushanbe"),
    ("post:Tanzania - Dar es Salaam", "Tanzania - Dar es Salaam"),
    ("post:Thailand - Bangkok", "Thailand - Bangkok"),
    ("post:Togo - Lome", "Togo - Lome"),
    ("post:Tonga - Nuku' alofa", "Tonga - Nuku' alofa"),
    ("post:Trinidad and Tobago - Port of Spain",
     "Trinidad and Tobago - Port of Spain"),
    ("post:Tunisia - Tunis", "Tunisia - Tunis"),
    ("post:Turkey - Ankara", "Turkey - Ankara"),
    ("post:Turkey - Istanbul", "Turkey - Istanbul"),
    ("post:Turkey - Izmir", "Turkey - Izmir"),
    ("post:Turkmenistan - Ashgabat", "Turkmenistan - Ashgabat"),
    ("post:Uganda - Kampala", "Uganda - Kampala"),
    ("post:Ukraine - Kyiv", "Ukraine - Kyiv"),
    ("post:UAE - Abu Dhabi", "UAE - Abu Dhabi"),
    ("post:UAE - Dubai", "UAE - Dubai"),
    ("post:UKREP", "UKREP"),
    ("post:USA - Atlanta", "USA - Atlanta"),
    ("post:USA - Boston", "USA - Boston"),
    ("post:USA - Chicago", "USA - Chicago"),
    ("post:USA - Houston", "USA - Houston"),
    ("post:USA - Los Angeles", "USA - Los Angeles"),
    ("post:USA - Miami", "USA - Miami"),
    ("post:USA - New York", "USA - New York"),
    ("post:USA - San Francisco", "USA - San Francisco"),
    ("post:USA - Washington DC", "USA - Washington DC"),
    ("post:Uruguay - Montevideo", "Uruguay - Montevideo"),
    ("post:Uzbekistan - Tashkent", "Uzbekistan - Tashkent"),
    ("post:Vanuatu - Port Vila", "Vanuatu - Port Vila"),
    ("post:Venezuela - Caracas", "Venezuela - Caracas"),
    ("post:Vietnam - Hanoi", "Vietnam - Hanoi"),
    ("post:Vietnam - Ho Chi Minh City", "Vietnam - Ho Chi Minh City"),
    ("post:Yemen - Sana'a", "Yemen - Sana'a"),
    ("post:Zambia - Lusaka", "Zambia - Lusaka"),
    ("post:Zimbabwe - Harare", "Zimbabwe - Harare"),
    # Trade Challenge Partners (TCP)
    ("tcp:1", "ADS Group"),
    ("tcp:2", "Agricultural Engineers Association Ltd"),
    ("tcp:3", "Amusement & Leisure Equipment Suppliers"),
    ("tcp:4", "Association of British Healthcare Industries"),
    ("tcp:5", "Association of British Mining Equipment Companies"),
    ("tcp:6", "Baby Products Association"),
    ("tcp:7", "BioPartner UK"),
    ("tcp:8", "Birmingham Chamber of Commerce"),
    ("tcp:9", "Brewing, Food & Beverage Industry Suppliers' Association"),
    ("tcp:10", "British Airport Services and Equipment Association"),
    ("tcp:11", "British Allied Trades Federation"),
    ("tcp:12", "British Aviation Group"),
    ("tcp:13", "British Contract Furnishing & Design Association"),
    ("tcp:14", "British Dental Industry Association"),
    ("tcp:15", "British Educational Suppliers Association"),
    ("tcp:16", "British Electrotechnical and Allied Manufacturers Association"),
    ("tcp:17", "British Equestrian Trade Association"),
    ("tcp:18", "British Footwear Association"),
    ("tcp:19", "British Furniture Manufacturers"),
    ("tcp:20", "British Home Enhancement Trade Association"),
    ("tcp:21", "British Marine Federation"),
    ("tcp:22", "British Pig Association"),
    ("tcp:23", "British Plastics Federation"),
    ("tcp:24", "British Promotional Merchandising Association"),
    ("tcp:25", "British Safety Industry Federation"),
    ("tcp:26", "British Security Industry Association"),
    ("tcp:27", "British Textile Machinery Association"),
    ("tcp:28", "British Water"),
    ("tcp:29", "Building Centre"),
    ("tcp:30", "Catering Equipment Suppliers Association"),
    ("tcp:31", "Chemical Industries Association"),
    ("tcp:32", "Children's Media Conference"),
    ("tcp:33", "Circuit Equipment and Materials Association / SCS"),
    ("tcp:34", "Commercial Horticultural Association"),
    ("tcp:35", "Composites UK"),
    ("tcp:36", "Construction Equipment Association"),
    ("tcp:37", "Construction Products Association"),
    ("tcp:38", "Craft Scotland"),
    ("tcp:39", "Crafts Council"),
    ("tcp:40", "Electronic Exporters Group / SCS"),
    ("tcp:41", "Energy Industries Council"),
    ("tcp:42", "Engineering Industries Association"),
    ("tcp:43", "English UK"),
    ("tcp:44", "Environmental Industries Commission"),
    ("tcp:45", "Federation of Environmental Trade Associations"),
    ("tcp:46", "Federation of Sports and Play Associations"),
    ("tcp:47", "Film Export UK"),
    ("tcp:48", "Food & Drink Exporters Association"),
    ("tcp:49", "GAMBICA"),
    ("tcp:50", "Gardenex & PetQuip: Federation of Garden & Leisure Manufacturers"),
    ("tcp:51", "Gun Trade Association"),
    ("tcp:52", "Hull & Humber Chamber of Commerce"),
    ("tcp:53", "Institute of Practitioners in Advertising"),
    ("tcp:54", "Lighting Industry Association"),
    ("tcp:55", "Manufacturing Technologies Association"),
    ("tcp:56", "Medilink UK"),
    ("tcp:57", "Midlands Aerospace Alliance"),
    ("tcp:58", "Motorsport Industry Association"),
    ("tcp:59", "Music Industries Association"),
    ("tcp:60", "National Microelectronics Institute"),
    ("tcp:61", "Pet Industry Federation"),
    ("tcp:62", "Processing & Packaging Machinery Association"),
    ("tcp:63", "Producers Alliance for Cinema & Television"),
    ("tcp:64", "Publishers Association"),
    ("tcp:65", "Railway Industry Association"),
    ("tcp:66", "RenewableUK"),
    ("tcp:67", "Society of Maritime Industries"),
    ("tcp:68", "Society of Motor Manufacturers & Traders Limited"),
    ("tcp:69", "Subsea UK"),
    ("tcp:70", "TechUK"),
    ("tcp:71", "The Deep End Ltd"),
    ("tcp:72", "UK Fashion & Textile Association"),
    ("tcp:73", "United Kingdom Interactive Entertainment Association"),
])

WIN_TYPES = (
    (1, "Export"),
    (2, "Non-export"),
    (3, "Both export and non-export"),
)

BREAKDOWN_TYPES = (
    (1, "Export"),
    (2, "Non-export"),
    (3, "Outward Direct Investment"),
)
BREAKDOWN_NAME_TO_ID = dict((v, k) for k, v in BREAKDOWN_TYPES)

NOTIFICATION_TYPES = (
    ('o', 'Officer'),
    ('c', 'Customer'),
)

TYPES_OF_SUPPORT = (
    (1, "Market entry advice and support – DIT/FCO in UK"),
    (2, "Missions, tradeshows and events (DIT/FCO)"),
    (3, "Advice, access and contacts – DIT/FCO Overseas"),
    (4, "Political and economic briefing"),
    (5, "Lobbying to overcome a problem – DIT/FCO"),
    (6, "Building positive reputation – DIT/FCO"),
    (7, "Non-export : Outward Direct Investment – FCO"),
    (8, "Non-export : Reduced tax burdens – FCO"),
    (9, "Non-export : New Business in UK/3rd market – FCO"),
    (10, "Non-export : Other – FCO"),
)

WITHOUT_OUR_SUPPORT = (
    (1, "No value without our help"),
    (2, "Up to 20% of the total expected value without our help"),
    (3, "Up to 40%"),
    (4, "Up to 60%"),
    (5, "Up to 80%"),
    (6, "More than 80%"),
    (7, "You could have won the entire value or similar without our help"),
)

# opposite of above for display to officers
WITH_OUR_SUPPORT = (
    (1, '100%',),
    (2, '80-99%',),
    (3, '60-79%',),
    (4, '40-59%',),
    (5, '20-39%',),
    (6, '1-19%',),
    (7, '0%',),
)

# noinspection PyTypeChecker
UK_REGIONS = Choices(
    ("EAST_MIDLANDS", 1, "East Midlands"),
    ("EAST", 2, "East of England"),
    ("LONDON", 3, "London"),
    ("NORTH_EAST", 4, "North East"),
    ("NORTH_WEST", 5, "North West"),
    ("NI", 6, "Northern Ireland"),
    ("SCOTLAND", 7, "Scotland"),
    ("SOUTH_EAST", 8, "South East"),
    ("SOUTH_WEST", 9, "South West"),
    ("WALES", 10, "Wales"),
    ("WEST_MIDLANDS", 11, "West Midlands"),
    ("YORKSHIRE", 12, "Yorkshire and The Humber"),
)

UK_SUPER_REGIONS = Choices(
    ("NORTH", 1, "Northern Powerhouse"),
    ("MIDLANDS", 2, "Midlands Engine"),
    ("LONDON", 3, "London"),
    ("SOUTH", 4, "South"),
    ("DEVOLVED", 5, "Devolved Administrations")
)

UK_REGIONS_MAP = {
    UK_SUPER_REGIONS.NORTH: {
        UK_REGIONS.NORTH_WEST: ['itt:The North West International Trade Team'],
        UK_REGIONS.NORTH_EAST: ['itt:DIT North East Regional International Trade Office'],
        UK_REGIONS.YORKSHIRE: [
            'itt:DIT Yorkshire',
            'itt:DIT Yorkshire and Humber Regional Sector Specialists'
        ]
    },
    UK_SUPER_REGIONS.MIDLANDS: {
        UK_REGIONS.EAST_MIDLANDS: ['itt:DIT Team East Midlands - International Trade Team'],
        UK_REGIONS.WEST_MIDLANDS: [
            'itt:DIT Team West Midlands - Birmingham',
            'itt:DIT Team West Midlands - Black Country',
            'itt:DIT Team West Midlands - Coventry',
            'itt:DIT Team West Midlands - Hereford and Worcester',
            'itt:DIT Team West Midlands - NEC',
            'itt:DIT Team West Midlands - Regional and LLP',
            'itt:DIT Team West Midlands - Shropshire',
            'itt:DIT Team West Midlands - Staffordshire',
            'itt:DIT West Midlands Team - Regional Team'
        ]
    },
    UK_SUPER_REGIONS.LONDON: {
        UK_REGIONS.LONDON: ['itt:London International Trade Team']
    },
    UK_SUPER_REGIONS.SOUTH: {
        UK_REGIONS.EAST: ['itt:DIT Team East'],
        UK_REGIONS.SOUTH_EAST: ['itt:DIT Team South East - International Trade Team'],
        UK_REGIONS.SOUTH_WEST: ['itt:DIT South West']
    },
    UK_SUPER_REGIONS.DEVOLVED: {
        UK_REGIONS.NI: ['itt:Invest Northern Ireland (Trade)'],
        UK_REGIONS.SCOTLAND: ['itt:Scottish Development International - International Trade Enquiries Team'],
        UK_REGIONS.WALES: ['itt:Welsh Government']
    }
}

BUSINESS_POTENTIAL = Choices(
    (
        'MEDIUM_OR_HIGH',
        1,
        "The company is a medium-sized business or an exporter with high potential"
    ),
    (
        'PART_MEDIUM_OR_HIGH',
        2,
        "The company exhibits characteristics of a medium-sized business or an exporter with high "
        "potential but does not meet the formal definition"
    ),
    (
        'NOT_MEDIUM_OR_HIGH',
        3,
        "The company is not a medium-sized business or an exporter with high potential"
    ),
)

EXPERIENCE_CATEGORIES = Choices(
    ('NEVER', 1, "Has never exported before"),
    ('STALE', 2, "Has exported before but not won an export order in the past twelve months"),
    ('NOPLAN', 3, "Has exported in the past twelve months but has not "
                  "won an export order proactively as a result of having an export plan"),
    ('NEW_MARKET', 7, "Is an exporter which did not receive or fulfil any export orders to this "
                      "market in the three financial years before this win"),
    ('GROWTH', 6, "Is an exporter that we are helping to maintain and grow its exports"),
    # Inactive
    ('SMALL', 4,
     "Is an exporter but exports currently account for less than 10% of its overall turnover"),
    ('MEDIUM', 5, "Is an exporter but has only won export orders in three countries or fewer"),
)

EXPERIENCE_CATEGORIES.add_subset('active', ['NEVER', 'STALE', 'NOPLAN', 'NEW_MARKET', 'GROWTH'])

EXPERIENCE_CATEGORIES.add_subset('new_exporter', ['NEVER', 'STALE', 'NOPLAN'])
EXPERIENCE_CATEGORIES.add_subset('sustainable', ['SMALL', 'MEDIUM'])
EXPERIENCE_CATEGORIES.add_subset('growth', ['GROWTH'])

MARKETING_SOURCE = (
    (1, "Business / professional contacts in the private sector"),
    (2, "Business / professional contacts in the public sector"),
    (3, "Articles/information I saw or read"),
    (4, "Advertisements I saw or read about the Exporting is GREAT campaign"),
    (5, "Great.gov.uk website"),
    (6, "Searched online"),
    (7, "Direct call from an international trade advisor"),
    (8, "The Exporting is GREAT truck"),
    (9, "UK trade fair"),
    (10, "Overseas trade fair"),
    (11, "Don’t know"),
    (12, "Other (please specify)"),
)
