# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, max_length=255)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
