# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0002_authorizationstate'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='authorizationstate',
            managers=[
            ],
        ),
    ]
