# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0003_auto_20171024_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationstate',
            name='next_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
