# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-17 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0032_hvc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='win',
            name='total_expected_export_value',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='win',
            name='total_expected_non_export_value',
            field=models.BigIntegerField(),
        ),
    ]
