# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-17 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0033_auto_20170317_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdown',
            name='value',
            field=models.BigIntegerField(),
        ),
    ]
