# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-14 16:32
from __future__ import unicode_literals

from django.db import migrations


def add_odi_breakdowns(apps, schema_editor):
    """ All wins going forward will have ODI breakdowns since the code does
    that and it makes reporting easier, so add them to historical wins

    """
    Win = apps.get_model('wins', 'Win')
    Breakdown = apps.get_model('wins', 'Breakdown')
    years = [2016 + i for i in range(0, 5)]
    for win in Win.objects.all():
        for year in years:
            Breakdown(
                win=win,
                type=3,
                value=0,
                year=year,
            ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0033_auto_20170308_1824'),
    ]

    operations = [
        migrations.RunPython(add_odi_breakdowns),
    ]
