# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-29 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0034_auto_20170317_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='win',
            name='export_experience',
            field=models.PositiveIntegerField(choices=[(1, 'has never exported before'), (2, 'has exported before but not won an export order in the past twelve months'), (3, 'has exported in the past twelve months but has not won an export order proactively as a result of having an export plan'), (4, 'is an exporter but exports currently account for less than 10% of its overall turnover'), (5, 'is an exporter but has only won export orders in three countries or fewer'), (6, 'is an exporter that we are helping to maintain and grow its exports')], null=True),
        ),
    ]
