# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-15 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0034_auto_20170314_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='win',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Export'), (2, 'Non-export'), (3, 'Both export and non-export')], null=True, verbose_name='Type of win'),
        ),
    ]
