# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-17 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0035_auto_20170315_1317'),
        ('wins', '0034_auto_20170317_1504'),
    ]

    operations = [
    ]
