# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-31 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0036_merge'),
        ('wins', '0035_auto_20170329_1535'),
    ]

    operations = [
    ]
