# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-04 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0036_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hvc',
            options={'ordering': ['name']},
        ),
        # add null
        migrations.AddField(
            model_name='hvc',
            name='financial_year',
            field=models.PositiveIntegerField(null=True),
        ),
        # move unique to both campaign and year
        migrations.AlterField(
            model_name='hvc',
            name='campaign_id',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterUniqueTogether(
            name='hvc',
            unique_together=set([('campaign_id', 'financial_year')]),
        ),
    ]
