# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-04 04:53
from __future__ import unicode_literals

from django.db import migrations


def do_thing(apps, schema_editor):
    HVC = apps.get_model('wins', 'HVC')

    new_hvcs_for_2017 = ['E218', 'E219','E220','E221','E222','E223','E224','E225','E226','E227','E228','E229','E230','E231','E232','E233','E234','E235','E236','E237','E238','E239','E240','E241']

    # add appropriate FY to existing hvcs
    for hvc in HVC.objects.all():
        if hvc.campaign_id in new_hvcs_for_2017:
            # does not exist in 2016, so just need to give it appropriate year
            hvc.financial_year = 17
            hvc.save()
        else:
            # all hvcs which aren't new for 2017 should exist for 2016
            hvc.financial_year = 16
            hvc.save()

    # manually make new ones

class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0038_auto_20170404_0452'),
    ]

    operations = [
        migrations.RunPython(do_thing),
    ]
