# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-04 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0039_auto_20170404_0453'),
    ]

    operations = [
        # remove null
        migrations.AlterField(
            model_name='hvc',
            name='financial_year',
            field=models.PositiveIntegerField(),
        ),
    ]
