# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-10 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0041_auto_20170405_1311'),
        ('wins', '0037_merge'),
    ]

    operations = [
    ]
