# Generated by Django 2.0.3 on 2018-03-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0045_auto_20180117_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerresponse',
            name='marketing_source',
            field=models.PositiveIntegerField(choices=[
                (1, 'Business / professional contacts in the private sector'),
                (2, 'Business / professional contacts in the public sector'),
                (3, 'Articles/information I saw or read'),
                (4, 'Advertisements I saw or read about the Exporting is GREAT campaign'),
                (5, 'Great.gov.uk website'),
                (6, 'Searched online'),
                (7, 'Direct call from an international trade advisor'),
                (8, 'The Exporting is GREAT truck'),
                (9, 'UK trade fair'),
                (10, 'Overseas trade fair'),
                (11, 'Other (please specify)'),
                (12, 'Don’t know')
            ],
                default=10,
                verbose_name='How did you first hear about DIT (or its predecessor, UKTI)'),
        ),
        migrations.AddField(
            model_name='customerresponse',
            name='other_marketing_source',
            field=models.CharField(max_length=256, null=True, verbose_name='Other marketing source'),
        ),
    ]
