# Generated by Django 2.0.3 on 2018-05-02 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0046_auto_20180327_1545'),
        ('wins', '0046_auto_20180328_1024'),
    ]

    operations = [
    ]
