# Generated by Django 2.0.6 on 2018-06-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0047_merge_20180502_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='win',
            name='export_experience',
            field=models.PositiveIntegerField(choices=[(1, 'Has never exported before'), (2, 'Has exported before but not won an export order in the past twelve months'), (3, 'Has exported in the past twelve months but has not won an export order proactively as a result of having an export plan'), (7, 'Is an exporter which did not receive or fulfil any export orders to this market between 1 April 2015 and 31 March 2018'), (6, 'Is an exporter that we are helping to maintain and grow its exports'), (4, 'Is an exporter but exports currently account for less than 10% of its overall turnover'), (5, 'Is an exporter but has only won export orders in three countries or fewer')], null=True),
        ),
    ]
