# Generated by Django 2.0.13 on 2019-10-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0049_add_business_potential'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='win',
            index=models.Index(fields=['created', 'id'], name='wins_win_created_d72f1e_idx'),
        ),
    ]
