# Generated by Django 2.2.10 on 2020-02-11 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('wins', '0051_auto_20200211_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedWin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wins.win',),
        ),
    ]
