# Generated by Django 2.2.10 on 2020-03-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0053_win_match_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='win',
            index=models.Index(fields=['match_id'], name='wins_win_match_i_f395ab_idx'),
        ),
    ]
