# Generated by Django 2.2.10 on 2020-03-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0053_auto_20200302_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='win',
            name='match_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='win',
            index=models.Index(fields=['match_id'], name='wins_win_match_i_f395ab_idx'),
        ),
    ]
